"""BOM (Bill of Materials) emitter — generates bom.md from a Bot."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from botcad.skeleton import Bot


def emit_bom(bot: Bot, output_dir: Path) -> None:
    """Generate bom.md with parts list, mass budget, and power budget."""
    lines: list[str] = []
    lines.append(f"# Bill of Materials — {bot.name}\n")
    lines.append("*Auto-generated by botcad*\n")

    # Collect all unique components
    components: dict[str, dict] = {}  # name -> {count, component, labels}

    for body in bot.all_bodies:
        for mount in body.mounts:
            c = mount.component
            if c.name not in components:
                components[c.name] = {
                    "component": c,
                    "count": 0,
                    "labels": [],
                    "bodies": [],
                }
            components[c.name]["count"] += 1
            components[c.name]["labels"].append(mount.label)
            components[c.name]["bodies"].append(body.name)

    # Count servos from joints
    servo_counts: dict[str, dict] = {}
    for joint in bot.all_joints:
        s = joint.servo
        if s.name not in servo_counts:
            servo_counts[s.name] = {
                "servo": s,
                "count": 0,
                "joints": [],
            }
        servo_counts[s.name]["count"] += 1
        servo_counts[s.name]["joints"].append(joint.name)

    # Parts table
    lines.append("## Parts\n")
    lines.append("| Part | Qty | Dimensions (mm) | Mass (g) | Notes |")
    lines.append("|------|-----|-----------------|----------|-------|")

    total_mass = 0.0

    for name, info in servo_counts.items():
        s = info["servo"]
        dims_mm = tuple(d * 1000 for d in s.dimensions)
        mass_g = s.mass * 1000
        total = info["count"] * s.mass
        total_mass += total
        joints_str = ", ".join(info["joints"])
        lines.append(
            f"| {name} | {info['count']} | "
            f"{dims_mm[0]:.1f} x {dims_mm[1]:.1f} x {dims_mm[2]:.1f} | "
            f"{mass_g:.0f} | Joints: {joints_str} |"
        )

    for name, info in components.items():
        c = info["component"]
        dims_mm = tuple(d * 1000 for d in c.dimensions)
        mass_g = c.mass * 1000
        total = info["count"] * c.mass
        total_mass += total
        labels_str = ", ".join(info["labels"])
        lines.append(
            f"| {name} | {info['count']} | "
            f"{dims_mm[0]:.1f} x {dims_mm[1]:.1f} x {dims_mm[2]:.1f} | "
            f"{mass_g:.0f} | {labels_str} |"
        )

    # Structural mass
    structural_mass = sum(b.solved_mass for b in bot.all_bodies) - total_mass
    if structural_mass > 0:
        lines.append(
            f"| Structural (printed) | — | — | {structural_mass * 1000:.0f} | "
            f"PLA/PETG frame |"
        )
        total_mass += structural_mass

    lines.append(f"| **Total** | | | **{total_mass * 1000:.0f}** | |")

    # Power budget
    lines.append("\n## Power Budget\n")
    lines.append("| Consumer | Voltage (V) | Current (A) | Power (W) |")
    lines.append("|----------|-------------|-------------|-----------|")

    total_power = 0.0
    for name, info in servo_counts.items():
        s = info["servo"]
        # Estimate average current at ~30% stall
        avg_current = s.stall_torque / (s.voltage * 0.3) if s.voltage > 0 else 0.5
        power = s.voltage * avg_current * info["count"]
        total_power += power
        lines.append(
            f"| {name} x{info['count']} | {s.voltage:.1f} | "
            f"~{avg_current * info['count']:.1f} | ~{power:.1f} |"
        )

    # Pi power
    pi_power = 5.0 * 0.6  # 5V, 600mA typical
    total_power += pi_power
    lines.append(f"| Raspberry Pi Zero 2W | 5.0 | 0.6 | {pi_power:.1f} |")

    lines.append(f"| **Total** | | | **~{total_power:.1f}** |")

    # Wire lengths
    if bot.wire_routes:
        lines.append("\n## Wire Lengths\n")
        lines.append("| Route | Type | Length (cm) | Slack (cm) |")
        lines.append("|-------|------|------------|------------|")
        for route in bot.wire_routes:
            length_cm = route.total_length * 100
            slack_cm = route.total_slack * 100
            lines.append(
                f"| {route.label} | {route.bus_type} | "
                f"{length_cm:.1f} | {slack_cm:.1f} |"
            )

    text = "\n".join(lines) + "\n"
    (output_dir / "bom.md").write_text(text)
    print(f"BOM: wrote bom.md to {output_dir}")
