"""BOM (Bill of Materials) emitter — generates bom.md from a Bot."""

from __future__ import annotations

from pathlib import Path

from botcad.skeleton import Bot


def _build_bom_lines(bodies: list, joints: list, title: str) -> list[str]:
    """Build BOM markdown lines from a set of bodies and joints."""
    lines: list[str] = []
    lines.append(f"# Bill of Materials — {title}\n")
    lines.append("*Auto-generated by botcad*\n")

    # Collect all unique components
    components: dict[str, dict] = {}  # name -> {count, component, labels}

    for body in bodies:
        for mount in body.mounts:
            c = mount.component
            if c.name not in components:
                components[c.name] = {
                    "component": c,
                    "count": 0,
                    "labels": [],
                    "bodies": [],
                }
            components[c.name]["count"] += 1
            components[c.name]["labels"].append(mount.label)
            components[c.name]["bodies"].append(body.name)

    # Count servos from joints
    servo_counts: dict[str, dict] = {}
    for joint in joints:
        s = joint.servo
        if s.name not in servo_counts:
            servo_counts[s.name] = {
                "servo": s,
                "count": 0,
                "joints": [],
            }
        servo_counts[s.name]["count"] += 1
        servo_counts[s.name]["joints"].append(joint.name)

    # Parts table
    lines.append("## Parts\n")
    lines.append("| Part | Qty | Dimensions (mm) | Mass (g) | Notes |")
    lines.append("|------|-----|-----------------|----------|-------|")

    total_mass = 0.0

    for name, info in servo_counts.items():
        s = info["servo"]
        dims_mm = tuple(d * 1000 for d in s.dimensions)
        mass_g = s.mass * 1000
        total = info["count"] * s.mass
        total_mass += total
        joints_str = ", ".join(info["joints"])
        lines.append(
            f"| {name} | {info['count']} | "
            f"{dims_mm[0]:.1f} x {dims_mm[1]:.1f} x {dims_mm[2]:.1f} | "
            f"{mass_g:.0f} | Joints: {joints_str} |"
        )

    for name, info in components.items():
        c = info["component"]
        dims_mm = tuple(d * 1000 for d in c.dimensions)
        mass_g = c.mass * 1000
        total = info["count"] * c.mass
        total_mass += total
        labels_str = ", ".join(info["labels"])
        lines.append(
            f"| {name} | {info['count']} | "
            f"{dims_mm[0]:.1f} x {dims_mm[1]:.1f} x {dims_mm[2]:.1f} | "
            f"{mass_g:.0f} | {labels_str} |"
        )

    # Structural mass
    structural_mass = sum(b.solved_mass for b in bodies) - total_mass
    if structural_mass > 0:
        lines.append(
            f"| Structural (printed) | — | — | {structural_mass * 1000:.0f} | "
            f"PLA/PETG frame |"
        )
        total_mass += structural_mass

    lines.append(f"| **Total** | | | **{total_mass * 1000:.0f}** | |")

    # Power budget — derived from actual components
    lines.append("\n## Power Budget\n")
    lines.append("| Consumer | Voltage (V) | Current (A) | Power (W) |")
    lines.append("|----------|-------------|-------------|-----------|")

    total_power = 0.0
    for name, info in servo_counts.items():
        s = info["servo"]
        avg_current = s.stall_torque / (s.voltage * 0.3) if s.voltage > 0 else 0.5
        power = s.voltage * avg_current * info["count"]
        total_power += power
        lines.append(
            f"| {name} x{info['count']} | {s.voltage:.1f} | "
            f"~{avg_current * info['count']:.1f} | ~{power:.1f} |"
        )

    # Add power for mounted compute/controller components (not servos)
    for name, info in components.items():
        c = info["component"]
        if c.voltage > 0 and c.typical_current > 0:
            p = c.voltage * c.typical_current * info["count"]
            total_power += p
            lines.append(
                f"| {name} x{info['count']} | {c.voltage:.1f} | "
                f"{c.typical_current:.1f} | {p:.1f} |"
            )

    lines.append(f"| **Total** | | | **~{total_power:.1f}** |")

    # ── Fastener inventory (with head type) ─────────────────────────
    # Key: (designation, head_type_label) -> count
    from botcad.fasteners import fastener_key

    fasteners: dict[tuple[str, str], int] = {}

    def _fastener_bom_key(mp) -> tuple[str, str]:
        ft, ht = fastener_key(mp)
        label = ht.replace("_", " ").title() if ht else "Socket Head Cap"
        return (ft, label)

    for joint in joints:
        s = joint.servo
        for ear in s.mounting_ears:
            k = _fastener_bom_key(ear)
            fasteners[k] = fasteners.get(k, 0) + 1
        for hp in s.horn_mounting_points:
            k = _fastener_bom_key(hp)
            fasteners[k] = fasteners.get(k, 0) + 1
        for hp in s.rear_horn_mounting_points:
            k = _fastener_bom_key(hp)
            fasteners[k] = fasteners.get(k, 0) + 1

    for body in bodies:
        for mount in body.mounts:
            for mp in mount.component.mounting_points:
                k = _fastener_bom_key(mp)
                fasteners[k] = fasteners.get(k, 0) + 1

    if fasteners:
        lines.append("\n## Fasteners\n")
        lines.append("| Fastener | Head Type | Qty | Usage |")
        lines.append("|----------|-----------|-----|-------|")

        # Build usage descriptions per fastener key
        usage: dict[tuple[str, str], list[str]] = {}
        for joint in joints:
            s = joint.servo
            ear_types: dict[tuple[str, str], int] = {}
            for ear in s.mounting_ears:
                k = _fastener_bom_key(ear)
                ear_types[k] = ear_types.get(k, 0) + 1
            for k, n in ear_types.items():
                usage.setdefault(k, []).append(
                    f"{n}x per joint bracket ({len(joints)} joints)"
                )

            horn_types: dict[tuple[str, str], int] = {}
            for hp in list(s.horn_mounting_points) + list(s.rear_horn_mounting_points):
                k = _fastener_bom_key(hp)
                horn_types[k] = horn_types.get(k, 0) + 1
            for k, n in horn_types.items():
                usage.setdefault(k, []).append(
                    f"{n}x per horn coupler ({len(joints)} joints)"
                )
            break  # all joints use the same servo type

        for body in bodies:
            for mount in body.mounts:
                comp_types: dict[tuple[str, str], int] = {}
                for mp in mount.component.mounting_points:
                    k = _fastener_bom_key(mp)
                    comp_types[k] = comp_types.get(k, 0) + 1
                for k, n in comp_types.items():
                    usage.setdefault(k, []).append(f"{n}x for {mount.component.name}")

        for k in sorted(fasteners):
            ft, ht = k
            desc = "; ".join(dict.fromkeys(usage.get(k, [])))  # deduplicate
            lines.append(f"| {ft} | {ht} | {fasteners[k]} | {desc} |")

    # ── Connector inventory ──────────────────────────────────────────
    connectors: dict[str, int] = {}
    for joint in joints:
        for wp in joint.servo.wire_ports:
            if wp.connector_type:
                connectors[wp.connector_type] = connectors.get(wp.connector_type, 0) + 1
    for body in bodies:
        for mount in body.mounts:
            for wp in mount.component.wire_ports:
                if wp.connector_type:
                    connectors[wp.connector_type] = (
                        connectors.get(wp.connector_type, 0) + 1
                    )

    if connectors:
        lines.append("\n## Connectors\n")
        lines.append("| Connector | Qty |")
        lines.append("|-----------|-----|")
        lines.extend(f"| {ct} | {connectors[ct]} |" for ct in sorted(connectors))

    return lines


def emit_bom(bot: Bot, output_dir: Path) -> None:
    """Generate bom.md with parts list, mass budget, and power budget."""
    lines = _build_bom_lines(bot.all_bodies, bot.all_joints, bot.name)

    # Wire lengths (full bot only)
    if bot.wire_routes:
        lines.append("\n## Wire Lengths\n")
        lines.append("| Route | Type | Length (cm) | Slack (cm) |")
        lines.append("|-------|------|------------|------------|")
        for route in bot.wire_routes:
            length_cm = route.total_length * 100
            slack_cm = route.total_slack * 100
            lines.append(
                f"| {route.label} | {route.bus_type} | "
                f"{length_cm:.1f} | {slack_cm:.1f} |"
            )

    text = "\n".join(lines) + "\n"
    (output_dir / "bom.md").write_text(text)
    print(f"BOM: wrote bom.md to {output_dir}")


def emit_bom_for_module(bot: Bot, module_name: str, output_dir: Path) -> None:
    """Generate a per-module BOM file."""
    bodies = bot._module_bodies(module_name)
    joints = bot._module_joints(module_name)
    if not bodies and not joints:
        return

    title = f"{bot.name} / {module_name}"
    lines = _build_bom_lines(bodies, joints, title)

    text = "\n".join(lines) + "\n"
    filename = f"bom_{module_name}.md"
    (output_dir / filename).write_text(text)
    print(f"BOM: wrote {filename}")
