"""CAD emitter — generates STEP assembly + per-body STLs using build123d.

Produces two outputs from the same geometry:

1. **Per-body STLs** — individual body solids in local frame, referenced by
   MuJoCo XML for simulation visuals. Same files a slicer would use.

2. **STEP assembly** — printable parts positioned and colored in world frame.
   Each printable part is a rigid group: bodies connected without servo joints
   are boolean-unioned into a single solid. Servo joints are the mechanical
   separation points — each side of a servo is a separate printed piece.

Bracket geometry is generated by botcad.bracket and unioned into the parent
body solid at each joint location. The bracket includes the servo pocket,
shaft clearance, screw holes, and cable exit.
"""

from __future__ import annotations

import logging
import math
from pathlib import Path
from typing import TYPE_CHECKING

from botcad.bracket import (
    BracketSpec,
    bracket_envelope,
    bracket_solid,
    coupler_solid,
    cradle_envelope,
    cradle_solid,
    horn_disc_params,
    servo_solid,
)
from botcad.component import BearingSpec, BusType, CameraSpec
from botcad.geometry import quat_to_euler
from botcad.skeleton import BodyShape, BracketStyle

log = logging.getLogger(__name__)

# PLA plastic density (kg/m³)
_PLA_DENSITY = 1200.0

if TYPE_CHECKING:
    from botcad.component import Component, Vec3
    from botcad.skeleton import Body, Bot, Joint


def _update_mass_from_solid(body: Body, solid) -> None:
    """Compute mass, COM, and inertia from the actual CAD solid + component masses.

    Structural mass uses an FDM print model: 2 perimeter walls + 20% infill.
    This matches real print settings better than solid volume × density.
    The solid's geometric properties (center, inertia) capture the actual shape
    including brackets, pockets, and clearance cuts.

    Component masses (battery, Pi, servos) are added via parallel axis theorem
    since they are purchased parts with known masses at known positions.
    """
    # --- Structural properties from actual geometry ---
    vol = solid.volume
    if vol <= 0:
        return  # degenerate solid, keep packing solver estimates

    # FDM print mass model: perimeter walls + sparse infill
    line_width = 0.0004  # 0.4mm nozzle
    n_walls = 2
    infill_fraction = 0.20
    wall_thickness = n_walls * line_width  # 0.8mm total perimeter
    wall_volume = solid.area * wall_thickness
    infill_volume = max(0.0, vol - wall_volume) * infill_fraction
    struct_mass = (wall_volume + infill_volume) * _PLA_DENSITY

    struct_com = solid.center()  # geometric centroid
    # matrix_of_inertia returns volumetric inertia about centroid.
    # Scale by effective_density (= struct_mass / vol) to get mass inertia
    # that accounts for the shape while using the correct total mass.
    mi = solid.matrix_of_inertia  # 3x3 list of lists
    effective_density = struct_mass / vol
    struct_ixx = mi[0][0] * effective_density
    struct_iyy = mi[1][1] * effective_density
    struct_izz = mi[2][2] * effective_density
    struct_ixy = mi[0][1] * effective_density
    struct_ixz = mi[0][2] * effective_density
    struct_iyz = mi[1][2] * effective_density

    # --- Component masses at their positions ---
    # (pos, mass, dims) for each component + servo
    mass_items: list[tuple[Vec3, float, Vec3]] = []

    for mount in body.mounts:
        mass_items.append(
            (mount.resolved_pos, mount.component.mass, mount.placed_dimensions)
        )

    # Servo mass at servo body center (not shaft/joint position)
    for joint in body.joints:
        mass_items.append(
            (joint.solved_servo_center, joint.servo.mass, joint.servo.dimensions)
        )

    # --- Composite mass ---
    total_mass = struct_mass + sum(m for _, m, _ in mass_items)
    if total_mass <= 0:
        total_mass = 0.01

    # --- Composite COM ---
    com_x = struct_com.X * struct_mass
    com_y = struct_com.Y * struct_mass
    com_z = struct_com.Z * struct_mass
    for pos, mass, _dims in mass_items:
        com_x += pos[0] * mass
        com_y += pos[1] * mass
        com_z += pos[2] * mass
    com_x /= total_mass
    com_y /= total_mass
    com_z /= total_mass

    # --- Composite inertia about composite COM ---
    # Start with structural inertia, shifted from structural centroid to composite COM
    sx = struct_com.X - com_x
    sy = struct_com.Y - com_y
    sz = struct_com.Z - com_z
    ixx = struct_ixx + struct_mass * (sy**2 + sz**2)
    iyy = struct_iyy + struct_mass * (sx**2 + sz**2)
    izz = struct_izz + struct_mass * (sx**2 + sy**2)
    ixy = struct_ixy + struct_mass * sx * sy
    ixz = struct_ixz + struct_mass * sx * sz
    iyz = struct_iyz + struct_mass * sy * sz

    # Add each component's inertia (box approximation shifted to composite COM)
    for pos, mass, dims in mass_items:
        if mass <= 0:
            continue
        dx, dy, dz = dims
        # Box inertia about own center
        ix = mass * (dy**2 + dz**2) / 12.0
        iy = mass * (dx**2 + dz**2) / 12.0
        iz = mass * (dx**2 + dy**2) / 12.0
        # Parallel axis shift to composite COM
        rx = pos[0] - com_x
        ry = pos[1] - com_y
        rz = pos[2] - com_z
        ixx += ix + mass * (ry**2 + rz**2)
        iyy += iy + mass * (rx**2 + rz**2)
        izz += iz + mass * (rx**2 + ry**2)
        ixy += mass * rx * ry
        ixz += mass * rx * rz
        iyz += mass * ry * rz

    # Ensure minimum inertia (MuJoCo needs positive values)
    min_i = 1e-8
    ixx = max(ixx, min_i)
    iyy = max(iyy, min_i)
    izz = max(izz, min_i)

    # Store results (overrides packing solver estimates)
    body.solved_mass = total_mass
    body.solved_com = (com_x, com_y, com_z)
    # fullinertia format: Ixx Iyy Izz Ixy Ixz Iyz
    body.solved_inertia = (ixx, iyy, izz, -ixy, -ixz, -iyz)

    log.info(
        "Mass from geometry: %s — %.1fg (struct %.1fg), COM (%.1f, %.1f, %.1f)mm",
        body.name,
        total_mass * 1000,
        struct_mass * 1000,
        com_x * 1000,
        com_y * 1000,
        com_z * 1000,
    )


def make_component_solid(component: Component):
    """Create a build123d solid representing a component's physical geometry.

    Used by component tear sheets to render actual CAD geometry instead of
    primitive approximations. Dispatches to shape-specific builders:
    - Wheels get tire ring + hub + bore via _make_wheel_solid()
    - Servos use body_dimensions (main block without ears/horn)
    - Everything else gets a box from dimensions
    """
    from build123d import Align, Box

    from botcad.component import ServoSpec

    dims = component.dimensions

    if component.name == "RaspberryPiZero2W":
        from botcad.components.compute import raspberry_pi_zero_solid

        return raspberry_pi_zero_solid()

    # Wheels: detailed tire/hub geometry
    if component.is_wheel:
        r = dims[0] / 2
        w = dims[2]
        return _make_wheel_solid(r, w)

    # Servos: use detailed solid from bracket module
    if isinstance(component, ServoSpec):
        from botcad.bracket import servo_solid

        return servo_solid(component)

    # Cameras: use detailed solid from camera module
    if isinstance(component, CameraSpec):
        from botcad.components.camera import camera_solid

        return camera_solid(component)

    # Batteries: use detailed solid from battery module
    from botcad.component import BatterySpec, BearingSpec

    if isinstance(component, BatterySpec):
        from botcad.components.battery import battery_solid

        return battery_solid(component)

    # Bearings: outer ring - inner bore
    if isinstance(component, BearingSpec):
        return _make_bearing_solid(component)

    # Test fastener prism: drilled holes at each mount point
    if component.name == "TestFastenerPrism":
        from botcad.components.test_fastener import test_fastener_solid

        return test_fastener_solid(component)

    return Box(
        dims[0],
        dims[1],
        dims[2],
        align=(Align.CENTER, Align.CENTER, Align.CENTER),
    )


def emit_cad(bot: Bot, output_dir: Path) -> None:
    """Generate STEP assembly and per-body STL files."""
    from build123d import Color, Compound, Location, export_step, export_stl

    from botcad.colors import COLOR_STRUCTURE_DARK, COLOR_STRUCTURE_HORN_DISC

    meshes_dir = output_dir / "meshes"
    meshes_dir.mkdir(parents=True, exist_ok=True)

    # Build body → parent joint mapping
    parent_joint_map: dict[str, Joint] = {}
    for joint in bot.all_joints:
        if joint.child is not None:
            parent_joint_map[joint.child.name] = joint

    # Compute world-frame position for each body (rest pose, all joints at 0)
    world_positions = _compute_world_positions(bot)

    # Group bodies into rigid parts (separated at servo joints)
    rigid_groups = _collect_rigid_groups(bot)

    # Collect per-body wire segments for channel cutting
    body_wire_segments: dict[str, list] = {}
    for route in bot.wire_routes:
        for seg in route.segments:
            body_wire_segments.setdefault(seg.body_name, []).append(
                (seg, route.bus_type)
            )

    # --- Per-body STLs (for MuJoCo sim) ---
    body_solids: dict[str, object] = {}
    for body in bot.all_bodies:
        pj = parent_joint_map.get(body.name)
        wire_segs = body_wire_segments.get(body.name, [])
        solid = _make_body_solid(body, pj, wire_segs)
        if solid is not None:
            body_solids[body.name] = solid
            export_stl(solid, str(meshes_dir / f"{body.name}.stl"))
            _update_mass_from_solid(body, solid)

    # --- Per-component STLs (for MuJoCo mesh geoms) ---
    # Each component gets its own STL at origin; MuJoCo positions it via pos/quat.
    comp_stl_count = 0
    for body in bot.all_bodies:
        if body.is_wheel_body:
            continue  # wheel mesh already represents the component
        for mount in body.mounts:
            comp_solid = make_component_solid(mount.component)
            if comp_solid is None:
                continue
            # If rotate_z, rotate the solid 90° around Z to match body frame
            if mount.rotate_z:
                comp_solid = comp_solid.locate(Location((0, 0, 0), (0, 0, 90)))
            stl_name = f"comp_{body.name}_{mount.label}.stl"
            export_stl(comp_solid, str(meshes_dir / stl_name))
            comp_stl_count += 1

    # --- Per-servo STLs (for MuJoCo mesh geoms) ---
    # Each servo gets an STL at origin; MuJoCo positions via servo_placement().
    servo_stl_cache: dict[str, str] = {}
    servo_stl_count = 0
    for body in bot.all_bodies:
        for joint in body.joints:
            servo = joint.servo
            # All servos of same model share the same base geometry
            if servo.name not in servo_stl_cache:
                s_solid = servo_solid(servo)
                stl_name = f"servo_{servo.name}.stl"
                export_stl(s_solid, str(meshes_dir / stl_name))
                servo_stl_cache[servo.name] = stl_name
                servo_stl_count += 1

    # --- Per-hardware STLs (for MuJoCo mesh geoms) ---
    # Many screws/pins share the same diameter/geometry.
    hardware_solids: dict[float, object] = {}
    for body in bot.all_bodies:
        # Hardware on joints
        for joint in body.joints:
            for ear in joint.servo.mounting_ears:
                if ear.diameter not in hardware_solids:
                    hardware_solids[ear.diameter] = _screw_solid(ear.diameter)
                    export_stl(
                        hardware_solids[ear.diameter],
                        str(meshes_dir / f"hardware_{ear.diameter:.4f}.stl"),
                    )
            for mp in joint.servo.horn_mounting_points:
                if mp.diameter not in hardware_solids:
                    hardware_solids[mp.diameter] = _screw_solid(mp.diameter)
                    export_stl(
                        hardware_solids[mp.diameter],
                        str(meshes_dir / f"hardware_{mp.diameter:.4f}.stl"),
                    )
            for mp in joint.servo.rear_horn_mounting_points:
                if mp.diameter not in hardware_solids:
                    hardware_solids[mp.diameter] = _screw_solid(mp.diameter)
                    export_stl(
                        hardware_solids[mp.diameter],
                        str(meshes_dir / f"hardware_{mp.diameter:.4f}.stl"),
                    )
        # Hardware on components
        for mount in body.mounts:
            for mp in mount.component.mounting_points:
                if mp.diameter not in hardware_solids:
                    hardware_solids[mp.diameter] = _screw_solid(mp.diameter)
                    export_stl(
                        hardware_solids[mp.diameter],
                        str(meshes_dir / f"hardware_{mp.diameter:.4f}.stl"),
                    )

    # --- Per-horn STLs ---
    for body in bot.all_bodies:
        for joint in body.joints:
            if not joint.servo.continuous:
                horn = _horn_solid(joint.servo)
                if horn:
                    export_stl(horn, str(meshes_dir / f"horn_{joint.name}.stl"))

    # --- Per-wire STLs ---
    from botcad.component import BusType

    bus_radii = {
        BusType.UART_HALF_DUPLEX: 0.0009,
        BusType.CSI: 0.0018,
        BusType.POWER: 0.0012,
    }
    for route in bot.wire_routes:
        radius = bus_radii.get(route.bus_type, 0.0015)
        for i, seg in enumerate(route.segments):
            if seg.straight_length < 0.001:
                continue
            wire_solid = _wire_segment_solid(seg.start, seg.end, radius)
            if wire_solid:
                # Wires are exported in their body-local frame
                export_stl(
                    wire_solid,
                    str(meshes_dir / f"wire_{route.label}_{seg.body_name}_{i}.stl"),
                )

    # --- STEP assembly (printable parts, positioned + colored) ---
    assembly_parts = []
    part_modules: list[str | None] = []  # parallel list: module name per part
    for group_name, bodies in rigid_groups.items():
        group_root = bodies[0]
        group_root_pos = world_positions[group_root.name]

        # Union all body solids in this rigid group
        group_solid = None
        for body in bodies:
            solid = body_solids.get(body.name)
            if solid is None:
                continue

            # Offset relative to group root
            body_pos = world_positions[body.name]
            rel = (
                body_pos[0] - group_root_pos[0],
                body_pos[1] - group_root_pos[1],
                body_pos[2] - group_root_pos[2],
            )
            if any(abs(c) > 1e-9 for c in rel):
                solid = solid.moved(Location(rel))

            if group_solid is None:
                group_solid = solid
            else:
                group_solid = group_solid + solid  # boolean union

        if group_solid is not None:
            # Boolean ops return Compound; extract the Solid so the STEP
            # exporter can write per-part colors correctly.
            group_solid = _as_solid(group_solid)
            group_solid.color = Color(*_body_color_rgb(group_root))
            group_solid.label = group_name
            positioned = group_solid.moved(Location(group_root_pos))
            assembly_parts.append(positioned)
            part_modules.append(group_root.module.name if group_root.module else None)

    # --- Horn discs (purchased parts, not in body STLs) ---
    for body in bot.all_bodies:
        body_world_pos = world_positions[body.name]
        for joint in body.joints:
            if joint.servo.continuous:
                continue
            params = horn_disc_params(joint.servo)
            if params is None:
                continue
            solid = _horn_solid(joint.servo)
            if solid is None:
                continue

            # Orient disc Z-axis to joint axis
            solid = _orient_z_to_axis(solid, joint.axis)

            # Joint world position + half-thickness offset along axis
            jx = body_world_pos[0] + joint.pos[0]
            jy = body_world_pos[1] + joint.pos[1]
            jz = body_world_pos[2] + joint.pos[2]
            ax, ay, az = joint.axis
            offset = params.thickness / 2
            pos = (jx + ax * offset, jy + ay * offset, jz + az * offset)

            solid.color = Color(*COLOR_STRUCTURE_HORN_DISC.rgb)
            solid.label = f"{joint.name}_horn"
            positioned = solid.moved(Location(pos))
            assembly_parts.append(positioned)
            # Horn belongs to parent body's module (joint owner)
            part_modules.append(body.module.name if body.module else None)

    # --- Servo solids (purchased parts, shown seated in brackets) ---
    servo_count = 0
    servo_solid_cache: dict[str, object] = {}
    for body in bot.all_bodies:
        body_world = world_positions[body.name]
        for joint in body.joints:
            servo = joint.servo
            center = joint.solved_servo_center
            euler = quat_to_euler(joint.solved_servo_quat)

            # Cache base solid by servo model (same geometry for all STS3215s)
            if servo.name not in servo_solid_cache:
                servo_solid_cache[servo.name] = servo_solid(servo)
            solid = servo_solid_cache[servo.name].moved(
                Location(body_world) * Location(center, euler)
            )
            solid = _as_solid(solid)

            solid.color = Color(*COLOR_STRUCTURE_DARK.rgb)
            solid.label = f"servo_{joint.name}"
            assembly_parts.append(solid)
            servo_count += 1

    if assembly_parts:
        assembly = Compound(label=bot.name, children=assembly_parts)
        export_step(
            assembly,
            str(output_dir / "assembly.step"),
            timestamp="2026-01-01T00:00:00",
        )
        print(
            f"CAD: wrote assembly.step ({len(assembly_parts) - servo_count} printed "
            f"+ {servo_count} servo parts) + {len(body_solids)} STLs to {output_dir}"
        )

    # Store for per-module export
    bot._assembly_parts = assembly_parts
    bot._part_modules = part_modules


def _compute_world_positions(bot: Bot) -> dict[str, tuple[float, float, float]]:
    """Walk kinematic tree, accumulate joint positions for rest pose.

    At rest (all joints at 0°), body frames are axis-aligned with their
    parents, so we just add joint.pos vectors up the chain.
    """
    positions: dict[str, tuple[float, float, float]] = {}

    def _walk(body: Body, parent_world_pos: tuple[float, float, float]) -> None:
        positions[body.name] = parent_world_pos
        for joint in body.joints:
            if joint.child is not None:
                child = joint.child
                # Wheel bodies are offset outward from the joint along the axis
                if child.is_wheel_body:
                    offset = joint.wheel_outboard_offset()
                    ax, ay, az = joint.axis
                    child_pos = (
                        parent_world_pos[0] + joint.pos[0] + ax * offset,
                        parent_world_pos[1] + joint.pos[1] + ay * offset,
                        parent_world_pos[2] + joint.pos[2] + az * offset,
                    )
                else:
                    child_pos = (
                        parent_world_pos[0] + joint.pos[0],
                        parent_world_pos[1] + joint.pos[1],
                        parent_world_pos[2] + joint.pos[2],
                    )
                _walk(joint.child, child_pos)

    if bot.root:
        _walk(bot.root, (0.0, 0.0, 0.0))
    return positions


def _collect_rigid_groups(bot: Bot) -> dict[str, list[Body]]:
    """Group bodies into printable rigid parts.

    Bodies separated by servo joints become separate parts. Bodies connected
    without a joint (rigidly welded in MuJoCo terms) are grouped together
    and will be boolean-unioned into a single solid.

    Currently every body-to-body connection goes through a servo joint, so
    each body is its own group. When the skeleton DSL supports rigid
    attachments (bodies without joints), this will group them.
    """
    groups: dict[str, list[Body]] = {}
    for body in bot.all_bodies:
        groups[body.name] = [body]
    return groups


def _body_color_rgb(body: Body) -> tuple[float, float, float]:
    """Pick RGB color for a body based on shape/role.

    Delegates to the shared implementation in mujoco.py so CAD and sim
    colors stay in sync.
    """
    from botcad.emit.mujoco import _body_color_rgb as _shared_body_color_rgb

    return _shared_body_color_rgb(body)


def _as_solid(shape):
    """Extract a single Solid from a boolean result.

    build123d boolean ops (cut, union) return a Compound even when the
    result is a single solid. The STEP exporter only writes colors on
    Solid objects, not Compounds. This extracts the Solid so colors
    work correctly in exported STEP files.
    """
    from build123d import Compound, Solid

    if isinstance(shape, Solid):
        return shape
    if isinstance(shape, Compound):
        solids = shape.solids()
        if len(solids) == 1:
            return solids[0]
    return shape


def _ensure_solid(shape):
    """Discard tiny sliver fragments from boolean ops, keep all substantial pieces.

    Boolean operations can produce tiny degenerate slivers at near-tangent
    intersections.  We discard fragments smaller than 1% of the total volume
    but keep all substantial disconnected pieces (e.g. body halves split by
    servo pockets).
    """
    from build123d import Compound, Solid

    if isinstance(shape, Solid):
        return shape
    # Compound or ShapeList — filter out tiny slivers
    solids = shape.solids() if hasattr(shape, "solids") else list(shape)
    if not solids:
        return shape
    if len(solids) == 1:
        return solids[0]
    vols = [(s, abs(s.volume)) for s in solids]
    total_vol = sum(v for _, v in vols)
    if total_vol < 1e-15:
        return shape
    threshold = total_vol * 0.01
    kept = [s for s, v in vols if v > threshold]
    if len(kept) == 1:
        return kept[0]
    if not kept:
        return max(vols, key=lambda sv: sv[1])[0]
    return Compound(children=kept)


def _to_compound(shape):
    """Ensure shape is a Compound (wrapping ShapeList or bare Solid)."""
    from build123d import Compound, Solid

    if isinstance(shape, Compound):
        return shape
    if isinstance(shape, Solid):
        return Compound(children=[shape])
    # ShapeList or other iterable
    return Compound(children=list(shape))


def _bboxes_overlap(a, b) -> bool:
    """Check if the bounding boxes of two shapes overlap."""
    if not (hasattr(a, "bounding_box") and hasattr(b, "bounding_box")):
        return True  # unknown type — assume overlap to be safe
    ab = a.bounding_box()
    bb = b.bounding_box()
    return (
        ab.min.X < bb.max.X
        and ab.max.X > bb.min.X
        and ab.min.Y < bb.max.Y
        and ab.max.Y > bb.min.Y
        and ab.min.Z < bb.max.Z
        and ab.max.Z > bb.min.Z
    )


def _bool_cut(shape, tool):
    """Boolean cut that works on Solid, Compound, or ShapeList."""
    from build123d import Solid

    if isinstance(shape, Solid):
        return shape.cut(tool)
    shape = _to_compound(shape)
    result = shape.cut(tool)
    return _to_compound(result)


def _cut_camera_features(shell, mount, body_dims, solved_dims):
    """Cut lens aperture and ribbon cable exit for a camera mount.

    - Lens aperture: cylinder through the body wall along the insertion axis
    - Ribbon slot: rectangular cutout for CSI ribbon cable to exit the body
    """
    from build123d import Align, Box, Cylinder, Location

    C = (Align.CENTER, Align.CENTER, Align.CENTER)
    cd = mount.component.dimensions
    pos = mount.resolved_pos
    ins = mount.resolved_insertion_axis  # outward normal of the mounting face

    # Lens aperture — 8mm diameter cylinder punched through the body wall.
    aperture_r = 0.004  # 4mm radius (covers Pi camera lens module)
    wall_depth = max(solved_dims) + 0.002  # long enough to cut through any wall

    # Euler angles to rotate cylinder (default Z-axis) to insertion axis
    ax, ay, az = ins
    if abs(ax) > 0.5:
        euler = (0, 90, 0)  # Z→X
    elif abs(ay) > 0.5:
        euler = (90, 0, 0)  # Z→Y
    else:
        euler = (0, 0, 0)  # already Z

    aperture = Cylinder(aperture_r, wall_depth, align=C)
    aperture = aperture.locate(Location((0, 0, 0), euler))
    aperture = aperture.locate(Location(pos))
    shell = shell - aperture

    # Ribbon cable exit slot — CSI ribbon is ~16mm wide x 1mm thick.
    ribbon_w = 0.017  # 17mm wide (16mm ribbon + clearance)
    ribbon_h = 0.002  # 2mm tall (1mm ribbon + clearance)

    # CSI port offset relative to camera center (from wire_ports)
    csi_ports = [wp for wp in mount.component.wire_ports if wp.bus_type is BusType.CSI]
    if csi_ports:
        wp = csi_ports[0]
        slot_pos = (pos[0] + wp.pos[0], pos[1] + wp.pos[1], pos[2] + wp.pos[2])
    else:
        slot_pos = (pos[0], pos[1], pos[2] - cd[1] / 2)

    # Slot oriented so the long dimension cuts through the body wall
    if abs(ax) > 0.5:
        ribbon_slot = Box(wall_depth, ribbon_w, ribbon_h, align=C)
    elif abs(ay) > 0.5:
        ribbon_slot = Box(ribbon_w, wall_depth, ribbon_h, align=C)
    else:
        ribbon_slot = Box(ribbon_w, ribbon_h, wall_depth, align=C)

    ribbon_slot = ribbon_slot.locate(Location(slot_pos))
    shell = shell - ribbon_slot

    return shell


def _make_body_solid(
    body: Body, parent_joint: Joint | None = None, wire_segments: list | None = None
):
    """Create a build123d solid for a body.

    Returns a Solid with:
    - Outer solid shape (no hollowing — fabrication shell pass comes later)
    - Servo brackets unioned in at each joint location
    - Component pockets cut out
    - Wire channels subtracted along routed cable paths

    Mesh origin conventions (matching MuJoCo emitter expectations):
    - box/sphere/cylinder: centered at origin
    - tube: offset so z=0 is the joint end, z=+length is the far end
    """
    from build123d import Align, Box, Cylinder, Location, Sphere

    C = (Align.CENTER, Align.CENTER, Align.CENTER)
    dims = body.dimensions

    if body.custom_solid is not None:
        shell = _ensure_solid(body.custom_solid)
    elif body.shape is BodyShape.CYLINDER:
        r = body.radius or dims[0] / 2
        h = body.width or dims[2]

        if body.is_wheel_body:
            # Wheels: centered on origin (hub at center)
            shell = _make_wheel_solid(r, h)
        elif parent_joint is not None:
            # Child cylinder: bottom face at origin (sits on top of horn).
            # Offset so z=0 is the joint/horn end, z=+h is the far end.
            shell = Cylinder(r, h, align=C)
            shell = shell.locate(Location((0, 0, h / 2)))
        else:
            shell = Cylinder(r, h, align=C)

        if parent_joint is not None:
            shell = _orient_z_to_axis(shell, parent_joint.axis, quat=body.frame_quat)

    elif body.shape is BodyShape.TUBE:
        r = body.outer_r or dims[0] / 2
        length = body.length or dims[2]
        shell = Cylinder(r, length, align=C)
        shell = shell.locate(Location((0, 0, length / 2)))

    elif body.shape is BodyShape.SPHERE:
        r = body.radius or dims[0] / 2
        shell = Sphere(r)

    elif body.shape is BodyShape.JAW:
        jw = body.jaw_width or dims[0]
        jt = body.jaw_thickness or dims[1]
        jl = body.jaw_length or dims[2]
        knuckle_h = 0.008  # thicker base for horn attachment
        # Knuckle at base (z=0 to z=knuckle_h)
        knuckle = Box(
            jw, jt * 2, knuckle_h, align=(Align.CENTER, Align.CENTER, Align.MIN)
        )
        # Jaw plate extending from knuckle to full length
        plate = Box(
            jw, jt, jl - knuckle_h, align=(Align.CENTER, Align.CENTER, Align.MIN)
        )
        plate = plate.locate(Location((0, 0, knuckle_h)))
        shell = knuckle + plate

    else:
        shell = Box(dims[0], dims[1], dims[2], align=C)

    # Cut component pockets (skip for wheel bodies — the wheel IS the component)
    if not body.is_wheel_body:
        for mount in body.mounts:
            cd = mount.placed_dimensions
            if isinstance(mount.component, BearingSpec):
                # Bearings: cylindrical pocket with tolerance
                tol = 0.0005  # 0.5mm total diameter clearance
                pocket_r = mount.component.od / 2 + tol / 2
                pocket_h = mount.component.width + 0.001  # through-cut margin
                pocket = Cylinder(pocket_r, pocket_h, align=C)
            else:
                # Default: box pocket
                pocket = Box(
                    cd[0] + 0.0005,
                    cd[1] + 0.0005,
                    cd[2] + 0.0005,
                    align=C,
                )
            pocket = pocket.locate(Location(mount.resolved_pos))
            shell = shell - pocket

            # Camera-specific cuts: lens aperture + ribbon cable exit
            if isinstance(mount.component, CameraSpec):
                shell = _cut_camera_features(shell, mount, body.dimensions, dims)

    # Union coupler onto child body for coupler-style joints.
    # The coupler is built in servo-local frame; place it so the shaft
    # center lands at the child body origin (joint point).
    bracket_spec = BracketSpec()
    if parent_joint is not None and parent_joint.bracket_style is BracketStyle.COUPLER:
        servo = parent_joint.servo
        # Quat is identical to solved_servo_quat (joint_pos only affects center).
        # Recompute center locally for child frame (shaft at origin).
        from botcad.geometry import rotate_vec

        quat = parent_joint.solved_servo_quat
        rotated_offset = rotate_vec(quat, servo.shaft_offset)
        center = (-rotated_offset[0], -rotated_offset[1], -rotated_offset[2])
        euler = quat_to_euler(quat)
        coupler = coupler_solid(servo, bracket_spec)
        coupler = coupler.locate(Location(center, euler))
        shell = _as_solid(shell.fuse(coupler))

    # Cut bracket footprints then union finished brackets at each joint.
    # Order matters: subtract envelope first so shell material doesn't
    # fill the servo pocket, then union the bracket (which has the pocket
    # already cut).  Result: (shell - envelope) + bracket
    for joint in body.joints:
        servo = joint.servo
        center = joint.solved_servo_center
        euler = quat_to_euler(joint.solved_servo_quat)

        if joint.bracket_style is BracketStyle.COUPLER:
            envelope = cradle_envelope(servo, bracket_spec)
            envelope = envelope.locate(Location(center, euler))
            cradle = cradle_solid(servo, bracket_spec)
            cradle = cradle.locate(Location(center, euler))
            shell = _to_compound(_bool_cut(shell, envelope).fuse(cradle))
        else:
            envelope = bracket_envelope(servo, bracket_spec)
            envelope = envelope.locate(Location(center, euler))
            bracket = bracket_solid(servo, bracket_spec)
            bracket = bracket.locate(Location(center, euler))
            shell = (shell - envelope) + bracket

    # Cut clearance volumes for rotating child bodies
    for joint in body.joints:
        if joint.child is not None:
            clearance = _child_clearance_volume(joint.child, joint)
            if clearance is not None and _bboxes_overlap(shell, clearance):
                shell = _bool_cut(shell, clearance)
                shell = _ensure_solid(shell)

    # Cut wire channels along routed cable paths
    if wire_segments:
        for seg, bus_type in wire_segments:
            channel = _wire_channel(seg, bus_type)
            if channel is not None and _bboxes_overlap(shell, channel):
                shell = _bool_cut(shell, channel)
                shell = _ensure_solid(shell)

    return shell


# Channel radii for wire routing (matches MuJoCo rendering radii)
_CHANNEL_RADIUS = {
    BusType.UART_HALF_DUPLEX: 0.0015,  # 1.5mm — servo bus
    BusType.CSI: 0.003,  # 3mm — CSI ribbon
    BusType.POWER: 0.002,  # 2mm — power cable
}


def _wire_channel(seg, bus_type: BusType):
    """Create a cylindrical channel solid along a wire segment.

    The channel uses the full cable radius so the wire fits inside.
    Returns None for degenerate (too-short) segments.
    """
    from build123d import Align, Cylinder, Location

    C = (Align.CENTER, Align.CENTER, Align.CENTER)

    dx = seg.end[0] - seg.start[0]
    dy = seg.end[1] - seg.start[1]
    dz = seg.end[2] - seg.start[2]
    length = math.sqrt(dx * dx + dy * dy + dz * dz)
    if length < 0.001:  # skip sub-millimeter segments
        return None

    radius = _CHANNEL_RADIUS.get(bus_type, 0.0015)

    mid = (
        (seg.start[0] + seg.end[0]) / 2,
        (seg.start[1] + seg.end[1]) / 2,
        (seg.start[2] + seg.end[2]) / 2,
    )
    # Rotate Z-aligned cylinder to match segment direction
    axis = (dx / length, dy / length, dz / length)
    ax, ay, az = axis

    if abs(az) > 0.999:
        if az < 0:
            quat = _axis_angle_to_quat((1, 0, 0), math.pi)
        else:
            quat = (1.0, 0.0, 0.0, 0.0)
    else:
        rot_angle = math.acos(max(-1.0, min(1.0, az)))
        rot_axis_x = -ay
        rot_axis_y = ax
        rot_mag = math.sqrt(rot_axis_x**2 + rot_axis_y**2)
        if rot_mag < 1e-9:
            quat = (1.0, 0.0, 0.0, 0.0)
        else:
            quat = _axis_angle_to_quat(
                (rot_axis_x / rot_mag, rot_axis_y / rot_mag, 0), rot_angle
            )

    euler = quat_to_euler(quat)
    channel = Cylinder(radius, length, align=C)
    return channel.locate(Location(mid, euler))


def _child_outer_envelope(child: Body, parent_joint: Joint):
    """Solid outer envelope of a child body, for clearance subtraction."""
    from build123d import Align, Box, Cylinder, Location, Sphere

    C = (Align.CENTER, Align.CENTER, Align.CENTER)
    dims = child.dimensions

    # Wheels need generous clearance for print tolerance, wobble, and debris.
    # Other child bodies just need FDM fit clearance.
    tol = 0.005 if child.is_wheel_body else 0.0005  # 5mm wheels, 0.5mm otherwise

    if child.shape is BodyShape.CYLINDER:
        r = (child.radius or dims[0] / 2) + tol
        nominal_h = child.width or child.height or dims[2]
        if child.is_wheel_body:
            # Only extend clearance outboard (away from bracket), not inboard.
            # Adding width tolerance inboard eats into the servo bracket.
            h = nominal_h + tol
            outer = Cylinder(r, h, align=C)
            # Shift outboard so inboard face stays at -nominal_h/2
            outer = outer.locate(Location((0, 0, tol / 2)))
        else:
            h = nominal_h + 2 * tol
            outer = Cylinder(r, h, align=C)
            # Match _make_body_solid: bottom face at origin for child cylinders
            outer = outer.locate(Location((0, 0, h / 2)))
        return _orient_z_to_axis(outer, parent_joint.axis, quat=child.frame_quat)

    elif child.shape is BodyShape.TUBE:
        r = (child.outer_r or dims[0] / 2) + tol
        length = (child.length or dims[2]) + tol
        outer = Cylinder(r, length, align=C)
        return outer.locate(Location((0, 0, length / 2)))  # z=0 at joint end

    elif child.shape is BodyShape.SPHERE:
        r = (child.radius or dims[0] / 2) + tol
        return Sphere(r)

    elif child.shape is BodyShape.JAW:
        jw = (child.jaw_width or dims[0]) + 2 * tol
        jt = (child.jaw_thickness or dims[1]) * 2 + 2 * tol  # knuckle is 2x thickness
        jl = (child.jaw_length or dims[2]) + tol
        outer = Box(jw, jt, jl, align=(Align.CENTER, Align.CENTER, Align.MIN))
        return outer

    else:  # box
        return Box(dims[0] + 2 * tol, dims[1] + 2 * tol, dims[2] + 2 * tol, align=C)


def _is_axially_symmetric(child: Body, joint: Joint) -> bool:
    """Check if child body is rotationally symmetric around the joint axis."""
    if child.shape is BodyShape.SPHERE:
        return True
    if child.shape is BodyShape.CYLINDER:
        # Cylinder gets oriented along parent_joint.axis via _orient_z_to_axis,
        # which is the same as the joint axis — so it's symmetric.
        return True
    return False


def _rotate_solid(solid, axis: tuple[float, float, float], angle_rad: float):
    """Rotate a solid around the given axis by angle_rad."""
    from build123d import Location

    if abs(angle_rad) < 1e-9:
        return solid
    quat = _axis_angle_to_quat(axis, angle_rad)
    euler = quat_to_euler(quat)
    return solid.moved(Location((0, 0, 0), euler))


def _child_clearance_volume(child: Body, joint: Joint):
    """Compute the volume swept by a child body through its joint range.

    For axially symmetric children (cylinders, spheres), the swept volume
    equals the static envelope. For asymmetric shapes, we union discrete
    rotations sampled every ~15 degrees through the joint range.
    """
    from build123d import Location

    envelope = _child_outer_envelope(child, joint)
    if envelope is None:
        return None

    if _is_axially_symmetric(child, joint):
        clearance = envelope
    else:
        lo, hi = joint.effective_range
        if lo == 0.0 and hi == 0.0:  # continuous rotation
            lo, hi = 0.0, 2 * math.pi

        range_deg = abs(math.degrees(hi - lo))
        n_samples = max(8, int(range_deg / 15))

        clearance = envelope  # angle=0 (rest pose)
        for i in range(1, n_samples + 1):
            angle = lo + (hi - lo) * i / n_samples
            rotated = _rotate_solid(envelope, joint.axis, angle)
            clearance = clearance + rotated  # boolean union

    # Position at joint.pos in parent frame, offset outboard for wheels
    if child.is_wheel_body:
        offset = joint.wheel_outboard_offset()
        ax, ay, az = joint.axis
        pos = (
            joint.pos[0] + ax * offset,
            joint.pos[1] + ay * offset,
            joint.pos[2] + az * offset,
        )
    else:
        pos = joint.pos
    return clearance.moved(Location(pos))


def _make_wheel_solid(radius: float, width: float):
    """Create a Pololu-style wheel: tire + rim + 6 spokes + hub + bore.

    Dimensions derived from the official Pololu STEP model (whe07a.STEP)
    for the 90x10mm servo wheel. Proportions are parameterized by radius
    and width so the same function works for other wheel sizes.

    Features:
        - 25T spline center bore (5.8mm)
        - 6x M3 mounting holes (1x 12.7mm pair, 2x 19.1mm pairs)
        - 6x M2 accessory slots in spokes
        - Tire treads (horizontal grooves)
    """
    from build123d import Align, Axis, Box, Cylinder, Location

    C = (Align.CENTER, Align.CENTER, Align.CENTER)

    # Radial dimensions (proportional to wheel radius R)
    tire_r = radius  # outer tire surface
    rim_outer_r = radius * 0.889  # tire inner / rim outer
    rim_inner_r = radius * 0.756  # rim inner / spoke outer
    spoke_inner_r = radius * 0.267  # spoke inner / hub outer
    hub_r = spoke_inner_r
    bore_r = 0.0029  # 5.8mm diameter (25T spline)

    # Axial widths
    tire_w = width
    rim_w = width
    spoke_w = width * 0.5
    hub_w = width * 0.68

    # --- Tire ring (silicone rubber) ---
    tire = Cylinder(tire_r, tire_w, align=C) - Cylinder(
        rim_outer_r, tire_w + 0.001, align=C
    )

    # --- Add Treads (horizontal grooves) ---
    n_treads = 60
    tread_w = 0.0015  # 1.5mm wide
    tread_depth = 0.0008  # 0.8mm deep
    for i in range(n_treads):
        angle = i * (360 / n_treads)
        tread = Box(tread_depth * 2, tire_w + 0.001, tread_w, align=C)
        tread = tread.locate(Location((radius, 0, 0), (0, angle, 0)))
        tire = tire - tread

    # --- Rim ring (plastic, tire seats on this) ---
    rim = Cylinder(rim_outer_r, rim_w, align=C) - Cylinder(
        rim_inner_r, rim_w + 0.001, align=C
    )

    # --- Hub disc ---
    hub = Cylinder(hub_r, hub_w, align=C)

    # --- Mounting Holes (6x M3) ---
    m3_r = 0.0016  # 3.2mm diameter
    for i in range(6):
        angle_rad = i * math.pi / 3
        # Alternate between 12.7mm and 19.1mm BCD (1 pair 12.7, 2 pairs 19.1)
        r_bcd = 0.00635 if (i % 3 == 0) else 0.00955
        mx = r_bcd * math.cos(angle_rad)
        my = r_bcd * math.sin(angle_rad)
        hole = Cylinder(m3_r, hub_w + 0.002, align=C)
        hole = hole.locate(Location((mx, my, 0)))
        hub = hub - hole

    # --- 6 spokes connecting hub to rim ---
    spoke_tangential = radius * 0.16
    spoke_length = rim_inner_r - spoke_inner_r + 0.004
    mid_r = (spoke_inner_r + rim_inner_r) / 2

    spokes = None
    for i in range(6):
        angle_rad = i * math.pi / 3
        angle_deg = math.degrees(angle_rad)
        cx = mid_r * math.cos(angle_rad)
        cy = mid_r * math.sin(angle_rad)

        spoke = Box(spoke_length, spoke_tangential, spoke_w, align=C)
        spoke = spoke.locate(Location((cx, cy, 0), (0, 0, angle_deg)))

        # --- Accessory Slot (M2) in spoke ---
        slot_r_start = spoke_inner_r + 0.006
        slot_r_end = rim_inner_r - 0.004
        slot_dia = 0.0022  # 2.2mm for M2 clearance
        slot_len = slot_r_end - slot_r_start
        slot_thick = spoke_w + 0.002
        slot_mid = (slot_r_start + slot_r_end) / 2

        # 3D Slot (Box + 2 Cylinders)
        s_box = Box(slot_len - slot_dia, slot_dia, slot_thick, align=C)
        c1 = Cylinder(slot_dia / 2, slot_thick, align=C).locate(
            Location(((slot_len - slot_dia) / 2, 0, 0))
        )
        c2 = Cylinder(slot_dia / 2, slot_thick, align=C).locate(
            Location((-(slot_len - slot_dia) / 2, 0, 0))
        )
        slot = s_box + c1 + c2

        slot = slot.locate(Location((slot_mid, 0, 0)))
        slot = slot.rotate(Axis.Z, angle_deg)
        spoke = spoke - slot

        if spokes is None:
            spokes = spoke
        else:
            spokes = spokes + spoke

    # --- Bore through full width ---
    bore = Cylinder(bore_r, width + 0.002, align=C)

    # Union order: hub + spokes + rim + tire - bore
    wheel = hub + spokes + rim + tire - bore
    return _as_solid(wheel)


def _horn_solid(servo):
    """Build a horn disc cylinder from servo specs."""
    from build123d import Align, Cylinder

    params = horn_disc_params(servo)
    if params is None:
        return None

    return Cylinder(
        params.radius,
        params.thickness,
        align=(Align.CENTER, Align.CENTER, Align.CENTER),
    )


def _orient_z_to_axis(
    solid,
    axis: tuple[float, float, float],
    quat: tuple[float, float, float, float] | None = None,
):
    """Rotate a solid from Z-up to align with the given axis.

    If *quat* is provided (e.g. from body.frame_quat), skip recomputation.
    """
    from build123d import Location

    if quat is not None:
        w, x, y, z = quat
        if abs(w - 1.0) < 1e-9 and abs(x) + abs(y) + abs(z) < 1e-9:
            return solid  # identity
        euler = quat_to_euler(quat)
        return solid.moved(Location((0, 0, 0), euler))

    ax, ay, az = axis
    # Compute rotation from Z to target axis
    angle_deg = math.degrees(math.acos(max(-1.0, min(1.0, az))))
    if angle_deg < 1e-4:
        return solid

    # Rotation axis in XY plane (cross product of Z=(0,0,1) and axis)
    rot_axis_x = -ay
    rot_axis_y = ax
    rot_mag = math.sqrt(rot_axis_x**2 + rot_axis_y**2)
    if rot_mag < 1e-9:
        # Opposite direction (az = -1)
        return solid.moved(Location((0, 0, 0), (180, 0, 0)))

    rot_axis_x /= rot_mag
    rot_axis_y /= rot_mag

    # Convert axis-angle to Euler angles for build123d Location
    q = _axis_angle_to_quat((rot_axis_x, rot_axis_y, 0.0), math.radians(angle_deg))
    euler = quat_to_euler(q)
    return solid.moved(Location((0, 0, 0), euler))


def _screw_solid(diameter: float):
    """Build a premium-looking screw solid (cylinder + chamfered head)."""
    from build123d import Align, Axis, Cylinder, chamfer

    # Generic screw: 1mm head height, 1.8x diameter head
    head_h = 0.001
    head_d = diameter * 1.8
    shank_h = 0.002  # just a nub for visualization

    head = Cylinder(head_d / 2, head_h, align=(Align.CENTER, Align.CENTER, Align.MIN))
    # Select the top face (max Z) for the head chamfer
    head_top_face = head.faces().sort_by(Axis.Z)[-1]
    head = chamfer(head_top_face.edges(), 0.2 * head_h)

    shank = Cylinder(
        diameter / 2, shank_h, align=(Align.CENTER, Align.CENTER, Align.MAX)
    )
    return head + shank


def _wire_segment_solid(start: Vec3, end: Vec3, radius: float):
    """Build a wire segment solid (cylinder with spherical caps)."""
    from build123d import Align, Cylinder, Location, Sphere

    dx = end[0] - start[0]
    dy = end[1] - start[1]
    dz = end[2] - start[2]
    length = math.sqrt(dx**2 + dy**2 + dz**2)
    if length < 1e-6:
        return None

    axis = (dx / length, dy / length, dz / length)
    mid = ((start[0] + end[0]) / 2, (start[1] + end[1]) / 2, (start[2] + end[2]) / 2)

    # Main cylinder
    cyl = Cylinder(radius, length, align=(Align.CENTER, Align.CENTER, Align.CENTER))
    # Spherical caps
    cap1 = Sphere(radius).moved(Location((0, 0, -length / 2)))
    cap2 = Sphere(radius).moved(Location((0, 0, length / 2)))

    wire = cyl + cap1 + cap2
    return _orient_z_to_axis(wire, axis).moved(Location(mid))


def _axis_angle_to_quat(
    axis: tuple[float, float, float], angle: float
) -> tuple[float, float, float, float]:
    """Convert axis-angle to quaternion (w, x, y, z)."""
    half = angle / 2
    s = math.sin(half)
    return (math.cos(half), axis[0] * s, axis[1] * s, axis[2] * s)


def _make_bearing_solid(bearing: BearingSpec):
    """Create a detailed solid for a ball bearing."""
    from build123d import Align, Cylinder

    C = (Align.CENTER, Align.CENTER, Align.CENTER)
    # Outer ring
    outer = Cylinder(bearing.od / 2, bearing.width, align=C)
    # Inner bore
    inner = Cylinder(bearing.id / 2, bearing.width + 0.001, align=C)

    return _as_solid(outer - inner)


def emit_cad_for_module(bot: Bot, module_name: str, output_dir: Path) -> None:
    """Export a per-module STEP file containing only parts in the named module."""
    from build123d import Compound, export_step

    assembly_parts = getattr(bot, "_assembly_parts", [])
    part_modules = getattr(bot, "_part_modules", [])

    module_parts = [
        part for part, mod in zip(assembly_parts, part_modules) if mod == module_name
    ]

    if module_parts:
        assembly = Compound(label=f"{bot.name}_{module_name}", children=module_parts)
        filename = f"assembly_{module_name}.step"
        export_step(
            assembly,
            str(output_dir / filename),
            timestamp="2026-01-01T00:00:00",
        )
        print(f"CAD: wrote {filename} ({len(module_parts)} parts)")
