"""CAD emitter — generates STEP assembly + per-body STLs using build123d.

Produces two outputs from the same geometry:

1. **Per-body STLs** — individual body solids in local frame, referenced by
   MuJoCo XML for simulation visuals. Same files a slicer would use.

2. **STEP assembly** — printable parts positioned and colored in world frame.
   Each printable part is a rigid group: bodies connected without servo joints
   are boolean-unioned into a single solid. Servo joints are the mechanical
   separation points — each side of a servo is a separate printed piece.

Bracket geometry is generated by botcad.bracket and unioned into the parent
body solid at each joint location. The bracket includes the servo pocket,
shaft clearance, screw holes, and cable exit.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

from botcad.bracket import (
    BracketSpec,
    bracket_envelope,
    bracket_solid,
    horn_disc_params,
    servo_solid,
)
from botcad.geometry import servo_placement

if TYPE_CHECKING:
    from botcad.component import Component
    from botcad.geometry import Quat
    from botcad.skeleton import Body, Bot, Joint


def make_component_solid(component: Component):
    """Create a build123d solid representing a component's physical geometry.

    Used by component tear sheets to render actual CAD geometry instead of
    primitive approximations. Dispatches to shape-specific builders:
    - Wheels get tire ring + hub + bore via _make_wheel_solid()
    - Servos use body_dimensions (main block without ears/horn)
    - Everything else gets a box from dimensions
    """
    from build123d import Align, Box

    from botcad.component import ServoSpec

    dims = component.dimensions

    # Wheels: detailed tire/hub geometry
    if "Wheel" in component.name:
        r = dims[0] / 2
        w = dims[2]
        return _make_wheel_solid(r, w)

    # Servos: use body_dimensions (without ears/horn) + shaft boss
    if isinstance(component, ServoSpec):
        dims = component.effective_body_dims

        body = Box(
            dims[0], dims[1], dims[2], align=(Align.CENTER, Align.CENTER, Align.CENTER)
        )

        if component.shaft_boss_radius > 0 and component.shaft_boss_height > 0:
            from build123d import Cylinder, Location

            boss = Cylinder(
                component.shaft_boss_radius,
                component.shaft_boss_height,
                align=(Align.CENTER, Align.CENTER, Align.MIN),
            )
            boss = boss.locate(
                Location(
                    (component.shaft_offset[0], component.shaft_offset[1], dims[2] / 2)
                )
            )
            body = body + boss

        return body

    return Box(
        dims[0],
        dims[1],
        dims[2],
        align=(Align.CENTER, Align.CENTER, Align.CENTER),
    )


def emit_cad(bot: Bot, output_dir: Path) -> None:
    """Generate STEP assembly and per-body STL files."""
    from build123d import Color, Compound, Location, export_step, export_stl

    meshes_dir = output_dir / "meshes"
    meshes_dir.mkdir(parents=True, exist_ok=True)

    # Build body → parent joint mapping
    parent_joint_map: dict[str, Joint] = {}
    for joint in bot.all_joints:
        if joint.child is not None:
            parent_joint_map[joint.child.name] = joint

    # Compute world-frame position for each body (rest pose, all joints at 0)
    world_positions = _compute_world_positions(bot)

    # Group bodies into rigid parts (separated at servo joints)
    rigid_groups = _collect_rigid_groups(bot)

    # Collect per-body wire segments for channel cutting
    body_wire_segments: dict[str, list] = {}
    for route in bot.wire_routes:
        for seg in route.segments:
            body_wire_segments.setdefault(seg.body_name, []).append(
                (seg, route.bus_type)
            )

    # --- Per-body STLs (for MuJoCo sim) ---
    body_solids: dict[str, object] = {}
    for body in bot.all_bodies:
        pj = parent_joint_map.get(body.name)
        wire_segs = body_wire_segments.get(body.name, [])
        solid = _make_body_solid(body, pj, wire_segs)
        if solid is not None:
            body_solids[body.name] = solid
            export_stl(solid, str(meshes_dir / f"{body.name}.stl"))

    # --- STEP assembly (printable parts, positioned + colored) ---
    assembly_parts = []
    part_modules: list[str | None] = []  # parallel list: module name per part
    for group_name, bodies in rigid_groups.items():
        group_root = bodies[0]
        group_root_pos = world_positions[group_root.name]

        # Union all body solids in this rigid group
        group_solid = None
        for body in bodies:
            solid = body_solids.get(body.name)
            if solid is None:
                continue

            # Offset relative to group root
            body_pos = world_positions[body.name]
            rel = (
                body_pos[0] - group_root_pos[0],
                body_pos[1] - group_root_pos[1],
                body_pos[2] - group_root_pos[2],
            )
            if any(abs(c) > 1e-9 for c in rel):
                solid = solid.moved(Location(rel))

            if group_solid is None:
                group_solid = solid
            else:
                group_solid = group_solid + solid  # boolean union

        if group_solid is not None:
            # Boolean ops return Compound; extract the Solid so the STEP
            # exporter can write per-part colors correctly.
            group_solid = _as_solid(group_solid)
            group_solid.color = Color(*_body_color_rgb(group_root))
            group_solid.label = group_name
            positioned = group_solid.moved(Location(group_root_pos))
            assembly_parts.append(positioned)
            part_modules.append(group_root.module.name if group_root.module else None)

    # --- Horn discs (purchased parts, not in body STLs) ---
    for body in bot.all_bodies:
        body_world_pos = world_positions[body.name]
        for joint in body.joints:
            if joint.servo.continuous:
                continue
            params = horn_disc_params(joint.servo)
            if params is None:
                continue
            solid = _horn_solid(joint.servo)
            if solid is None:
                continue

            # Orient disc Z-axis to joint axis
            solid = _orient_z_to_axis(solid, joint.axis)

            # Joint world position + half-thickness offset along axis
            jx = body_world_pos[0] + joint.pos[0]
            jy = body_world_pos[1] + joint.pos[1]
            jz = body_world_pos[2] + joint.pos[2]
            ax, ay, az = joint.axis
            offset = params.thickness / 2
            pos = (jx + ax * offset, jy + ay * offset, jz + az * offset)

            solid.color = Color(0.85, 0.85, 0.88)
            solid.label = f"{joint.name}_horn"
            positioned = solid.moved(Location(pos))
            assembly_parts.append(positioned)
            # Horn belongs to parent body's module (joint owner)
            part_modules.append(body.module.name if body.module else None)

    # --- Servo solids (purchased parts, shown seated in brackets) ---
    servo_count = 0
    servo_solid_cache: dict[str, object] = {}
    for body in bot.all_bodies:
        body_world = world_positions[body.name]
        for joint in body.joints:
            servo = joint.servo
            center, quat = servo_placement(
                servo.shaft_offset, servo.shaft_axis, joint.axis, joint.pos
            )
            euler = _quat_to_euler(quat)

            # Cache base solid by servo model (same geometry for all STS3215s)
            if servo.name not in servo_solid_cache:
                servo_solid_cache[servo.name] = servo_solid(servo)
            solid = servo_solid_cache[servo.name].moved(
                Location(body_world) * Location(center, euler)
            )
            solid = _as_solid(solid)
            solid.color = Color(0.15, 0.15, 0.15)  # dark gray
            solid.label = f"servo_{joint.name}"
            assembly_parts.append(solid)
            servo_count += 1

    if assembly_parts:
        assembly = Compound(label=bot.name, children=assembly_parts)
        export_step(assembly, str(output_dir / "assembly.step"))
        print(
            f"CAD: wrote assembly.step ({len(assembly_parts) - servo_count} printed "
            f"+ {servo_count} servo parts) + {len(body_solids)} STLs to {output_dir}"
        )

    # Store for per-module export
    bot._assembly_parts = assembly_parts
    bot._part_modules = part_modules


def _compute_world_positions(bot: Bot) -> dict[str, tuple[float, float, float]]:
    """Walk kinematic tree, accumulate joint positions for rest pose.

    At rest (all joints at 0°), body frames are axis-aligned with their
    parents, so we just add joint.pos vectors up the chain.
    """
    positions: dict[str, tuple[float, float, float]] = {}

    def _walk(body: Body, parent_world_pos: tuple[float, float, float]) -> None:
        positions[body.name] = parent_world_pos
        for joint in body.joints:
            if joint.child is not None:
                child_pos = (
                    parent_world_pos[0] + joint.pos[0],
                    parent_world_pos[1] + joint.pos[1],
                    parent_world_pos[2] + joint.pos[2],
                )
                _walk(joint.child, child_pos)

    if bot.root:
        _walk(bot.root, (0.0, 0.0, 0.0))
    return positions


def _collect_rigid_groups(bot: Bot) -> dict[str, list[Body]]:
    """Group bodies into printable rigid parts.

    Bodies separated by servo joints become separate parts. Bodies connected
    without a joint (rigidly welded in MuJoCo terms) are grouped together
    and will be boolean-unioned into a single solid.

    Currently every body-to-body connection goes through a servo joint, so
    each body is its own group. When the skeleton DSL supports rigid
    attachments (bodies without joints), this will group them.
    """
    groups: dict[str, list[Body]] = {}
    for body in bot.all_bodies:
        groups[body.name] = [body]
    return groups


def _body_color_rgb(body: Body) -> tuple[float, float, float]:
    """Pick RGB color for a body based on shape/role.

    Delegates to the shared implementation in mujoco.py so CAD and sim
    colors stay in sync.
    """
    from botcad.emit.mujoco import _body_color_rgb as _shared_body_color_rgb

    return _shared_body_color_rgb(body)


def _as_solid(shape):
    """Extract a single Solid from a boolean result.

    build123d boolean ops (cut, union) return a Compound even when the
    result is a single solid. The STEP exporter only writes colors on
    Solid objects, not Compounds. This extracts the Solid so colors
    work correctly in exported STEP files.
    """
    from build123d import Compound, Solid

    if isinstance(shape, Solid):
        return shape
    if isinstance(shape, Compound):
        solids = shape.solids()
        if len(solids) == 1:
            return solids[0]
    return shape


def _ensure_solid(shape):
    """Keep only the largest solid when a boolean op fragments the body."""
    from build123d import Solid

    if isinstance(shape, Solid):
        return shape
    # Compound or ShapeList — pick the largest piece by volume
    solids = shape.solids() if hasattr(shape, "solids") else list(shape)
    if not solids:
        return shape
    return max(solids, key=lambda s: abs(s.volume))


def _make_body_solid(
    body: Body, parent_joint: Joint | None = None, wire_segments: list | None = None
):
    """Create a build123d solid for a body.

    Returns a Solid with:
    - Outer solid shape (no hollowing — fabrication shell pass comes later)
    - Servo brackets unioned in at each joint location
    - Component pockets cut out
    - Wire channels subtracted along routed cable paths

    Mesh origin conventions (matching MuJoCo emitter expectations):
    - box/sphere/cylinder: centered at origin
    - tube: offset so z=0 is the joint end, z=+length is the far end
    """
    from build123d import Align, Box, Cylinder, Location, Sphere

    C = (Align.CENTER, Align.CENTER, Align.CENTER)
    dims = body.dimensions

    if body.shape == "cylinder":
        r = body.radius or dims[0] / 2
        h = body.width or dims[2]

        has_wheel = any("Wheel" in m.component.name for m in body.mounts)
        if has_wheel:
            # Wheels: centered on origin (hub at center)
            shell = _make_wheel_solid(r, h)
        elif parent_joint is not None:
            # Child cylinder: bottom face at origin (sits on top of horn).
            # Offset so z=0 is the joint/horn end, z=+h is the far end.
            shell = Cylinder(r, h, align=C)
            shell = shell.locate(Location((0, 0, h / 2)))
        else:
            shell = Cylinder(r, h, align=C)

        if parent_joint is not None:
            shell = _orient_z_to_axis(shell, parent_joint.axis)

    elif body.shape == "tube":
        r = body.outer_r or dims[0] / 2
        length = body.length or dims[2]
        shell = Cylinder(r, length, align=C)
        shell = shell.locate(Location((0, 0, length / 2)))

    elif body.shape == "sphere":
        r = body.radius or dims[0] / 2
        shell = Sphere(r)

    elif body.shape == "jaw":
        jw = body.jaw_width or dims[0]
        jt = body.jaw_thickness or dims[1]
        jl = body.jaw_length or dims[2]
        knuckle_h = 0.008  # thicker base for horn attachment
        # Knuckle at base (z=0 to z=knuckle_h)
        knuckle = Box(
            jw, jt * 2, knuckle_h, align=(Align.CENTER, Align.CENTER, Align.MIN)
        )
        # Jaw plate extending from knuckle to full length
        plate = Box(
            jw, jt, jl - knuckle_h, align=(Align.CENTER, Align.CENTER, Align.MIN)
        )
        plate = plate.locate(Location((0, 0, knuckle_h)))
        shell = knuckle + plate

    else:
        shell = Box(dims[0], dims[1], dims[2], align=C)

    # Cut component pockets (skip for wheel bodies — the wheel IS the component)
    is_wheel_body = any("Wheel" in m.component.name for m in body.mounts)
    if not is_wheel_body:
        for mount in body.mounts:
            cd = mount.component.dimensions
            pocket = Box(
                cd[0] + 0.0005,
                cd[1] + 0.0005,
                cd[2] + 0.0005,
                align=(Align.CENTER, Align.CENTER, Align.CENTER),
            )
            pocket = pocket.locate(Location(mount.resolved_pos))
            shell = shell - pocket

    # Cut bracket footprints then union finished brackets at each joint.
    # Order matters: subtract envelope first so shell material doesn't
    # fill the servo pocket, then union the bracket (which has the pocket
    # already cut).  Result: (shell - envelope) + bracket
    bracket_spec = BracketSpec()
    for joint in body.joints:
        servo = joint.servo
        center, quat = servo_placement(
            servo.shaft_offset, servo.shaft_axis, joint.axis, joint.pos
        )
        euler = _quat_to_euler(quat)

        envelope = bracket_envelope(servo, bracket_spec)
        envelope = envelope.locate(Location(center, euler))

        # Wheel joints: cut pocket only, no bracket union.
        # Solid body material provides structural support; adding bracket
        # walls would protrude past the body surface and collide with the wheel.
        child_has_wheel = joint.child is not None and any(
            "Wheel" in m.component.name for m in joint.child.mounts
        )
        if child_has_wheel:
            shell = shell - envelope
        else:
            bracket = bracket_solid(servo, bracket_spec)
            bracket = bracket.locate(Location(center, euler))
            shell = (shell - envelope) + bracket

    # Cut clearance volumes for rotating child bodies
    for joint in body.joints:
        if joint.child is not None:
            clearance = _child_clearance_volume(joint.child, joint)
            if clearance is not None:
                shell = shell - clearance
                shell = _ensure_solid(shell)

    # Cut wire channels along routed cable paths
    if wire_segments:
        for seg, bus_type in wire_segments:
            channel = _wire_channel(seg, bus_type)
            if channel is not None:
                shell = shell - channel
                shell = _ensure_solid(shell)

    return shell


# Channel radii for wire routing (matches MuJoCo rendering radii)
_CHANNEL_RADIUS = {
    "uart_half_duplex": 0.0015,  # 1.5mm — servo bus
    "csi": 0.003,  # 3mm — CSI ribbon
    "power": 0.002,  # 2mm — power cable
}


def _wire_channel(seg, bus_type: str):
    """Create a cylindrical channel solid along a wire segment.

    The channel uses the full cable radius so the wire fits inside.
    Returns None for degenerate (too-short) segments.
    """
    from build123d import Align, Cylinder, Location

    C = (Align.CENTER, Align.CENTER, Align.CENTER)

    dx = seg.end[0] - seg.start[0]
    dy = seg.end[1] - seg.start[1]
    dz = seg.end[2] - seg.start[2]
    length = math.sqrt(dx * dx + dy * dy + dz * dz)
    if length < 0.001:  # skip sub-millimeter segments
        return None

    radius = _CHANNEL_RADIUS.get(bus_type, 0.0015)

    mid = (
        (seg.start[0] + seg.end[0]) / 2,
        (seg.start[1] + seg.end[1]) / 2,
        (seg.start[2] + seg.end[2]) / 2,
    )
    # Rotate Z-aligned cylinder to match segment direction
    axis = (dx / length, dy / length, dz / length)
    ax, ay, az = axis

    if abs(az) > 0.999:
        if az < 0:
            quat = _axis_angle_to_quat((1, 0, 0), math.pi)
        else:
            quat = (1.0, 0.0, 0.0, 0.0)
    else:
        rot_angle = math.acos(max(-1.0, min(1.0, az)))
        rot_axis_x = -ay
        rot_axis_y = ax
        rot_mag = math.sqrt(rot_axis_x**2 + rot_axis_y**2)
        if rot_mag < 1e-9:
            quat = (1.0, 0.0, 0.0, 0.0)
        else:
            quat = _axis_angle_to_quat(
                (rot_axis_x / rot_mag, rot_axis_y / rot_mag, 0), rot_angle
            )

    euler = _quat_to_euler(quat)
    channel = Cylinder(radius, length, align=C)
    return channel.locate(Location(mid, euler))


def _child_outer_envelope(child: Body, parent_joint: Joint):
    """Solid outer envelope of a child body, for clearance subtraction."""
    from build123d import Align, Box, Cylinder, Location, Sphere

    C = (Align.CENTER, Align.CENTER, Align.CENTER)
    tol = 0.0005  # 0.5mm clearance per side
    dims = child.dimensions

    if child.shape == "cylinder":
        r = (child.radius or dims[0] / 2) + tol
        h = (child.width or child.height or dims[2]) + 2 * tol
        has_wheel = any("Wheel" in m.component.name for m in child.mounts)
        outer = Cylinder(r, h, align=C)
        if not has_wheel:
            # Match _make_body_solid: bottom face at origin for child cylinders
            outer = outer.locate(Location((0, 0, h / 2)))
        return _orient_z_to_axis(outer, parent_joint.axis)

    elif child.shape == "tube":
        r = (child.outer_r or dims[0] / 2) + tol
        length = (child.length or dims[2]) + tol
        outer = Cylinder(r, length, align=C)
        return outer.locate(Location((0, 0, length / 2)))  # z=0 at joint end

    elif child.shape == "sphere":
        r = (child.radius or dims[0] / 2) + tol
        return Sphere(r)

    elif child.shape == "jaw":
        jw = (child.jaw_width or dims[0]) + 2 * tol
        jt = (child.jaw_thickness or dims[1]) * 2 + 2 * tol  # knuckle is 2x thickness
        jl = (child.jaw_length or dims[2]) + tol
        outer = Box(jw, jt, jl, align=(Align.CENTER, Align.CENTER, Align.MIN))
        return outer

    else:  # box
        return Box(dims[0] + 2 * tol, dims[1] + 2 * tol, dims[2] + 2 * tol, align=C)


def _is_axially_symmetric(child: Body, joint: Joint) -> bool:
    """Check if child body is rotationally symmetric around the joint axis."""
    if child.shape == "sphere":
        return True
    if child.shape == "cylinder":
        # Cylinder gets oriented along parent_joint.axis via _orient_z_to_axis,
        # which is the same as the joint axis — so it's symmetric.
        return True
    return False


def _rotate_solid(solid, axis: tuple[float, float, float], angle_rad: float):
    """Rotate a solid around the given axis by angle_rad."""
    from build123d import Location

    if abs(angle_rad) < 1e-9:
        return solid
    quat = _axis_angle_to_quat(axis, angle_rad)
    euler = _quat_to_euler(quat)
    return solid.moved(Location((0, 0, 0), euler))


def _child_clearance_volume(child: Body, joint: Joint):
    """Compute the volume swept by a child body through its joint range.

    For axially symmetric children (cylinders, spheres), the swept volume
    equals the static envelope. For asymmetric shapes, we union discrete
    rotations sampled every ~15 degrees through the joint range.
    """
    from build123d import Location

    envelope = _child_outer_envelope(child, joint)
    if envelope is None:
        return None

    if _is_axially_symmetric(child, joint):
        clearance = envelope
    else:
        lo, hi = joint.effective_range
        if lo == 0.0 and hi == 0.0:  # continuous rotation
            lo, hi = 0.0, 2 * math.pi

        range_deg = abs(math.degrees(hi - lo))
        n_samples = max(8, int(range_deg / 15))

        clearance = envelope  # angle=0 (rest pose)
        for i in range(1, n_samples + 1):
            angle = lo + (hi - lo) * i / n_samples
            rotated = _rotate_solid(envelope, joint.axis, angle)
            clearance = clearance + rotated  # boolean union

    # Position at joint.pos in parent frame
    return clearance.moved(Location(joint.pos))


def _make_wheel_solid(radius: float, width: float):
    """Create a Pololu-style wheel: tire + rim + 6 spokes + hub + bore.

    Dimensions derived from the official Pololu STEP model (whe07a.STEP)
    for the 90x10mm servo wheel. Proportions are parameterized by radius
    and width so the same function works for other wheel sizes.

    Cross-section profile (from STEP face analysis):
        Tire:   r=0.89R–R,   full width    (silicone rubber outer ring)
        Rim:    r=0.76R–0.89R, full width   (plastic rim, tire seats here)
        Spokes: r=0.27R–0.76R, 50% width   (6 spokes, narrower than rim)
        Hub:    r=bore–0.27R, 68% width     (center disc with spline bore)
    """
    from build123d import Align, Box, Cylinder, Location

    C = (Align.CENTER, Align.CENTER, Align.CENTER)

    # Radial dimensions (proportional to wheel radius)
    tire_r = radius  # outer tire surface
    rim_outer_r = radius * 0.889  # tire inner / rim outer
    rim_inner_r = radius * 0.756  # rim inner / spoke outer
    spoke_inner_r = radius * 0.267  # spoke inner / hub outer
    hub_r = spoke_inner_r
    bore_r = 0.0029  # 5.8mm diameter (25T spline)

    # Axial widths (from STEP X-extent analysis)
    tire_w = width  # full width
    rim_w = width  # rim also full width
    spoke_w = width * 0.5  # spokes narrower
    hub_w = width * 0.68  # hub disc slightly wider than spokes

    # Spoke cross-section
    spoke_tangential = radius * 0.16  # ~7mm for 90mm wheel
    spoke_length = rim_inner_r - spoke_inner_r + 0.004  # +2mm overlap each end

    # --- Tire ring (silicone rubber) ---
    tire = Cylinder(tire_r, tire_w, align=C) - Cylinder(
        rim_outer_r, tire_w + 0.001, align=C
    )

    # --- Rim ring (plastic, tire seats on this) ---
    rim = Cylinder(rim_outer_r, rim_w, align=C) - Cylinder(
        rim_inner_r, rim_w + 0.001, align=C
    )

    # --- Hub disc ---
    hub = Cylinder(hub_r, hub_w, align=C) - Cylinder(bore_r, hub_w + 0.001, align=C)

    # --- 6 spokes connecting hub to rim ---
    spokes = None
    mid_r = (spoke_inner_r + rim_inner_r) / 2
    for i in range(6):
        angle_rad = i * math.pi / 3
        angle_deg = math.degrees(angle_rad)
        cx = mid_r * math.cos(angle_rad)
        cy = mid_r * math.sin(angle_rad)

        spoke = Box(spoke_length, spoke_tangential, spoke_w, align=C)
        spoke = spoke.locate(Location((cx, cy, 0), (0, 0, angle_deg)))

        if spokes is None:
            spokes = spoke
        else:
            spokes = spokes + spoke

    # --- Bore through full width ---
    bore = Cylinder(bore_r, width + 0.002, align=C)

    # Union order matters: each step must add geometry that touches the
    # previous result. Hub→spokes→rim→tire (inside out).
    wheel = hub + spokes + rim + tire - bore
    return _as_solid(wheel)


def _horn_solid(servo):
    """Build a horn disc cylinder from servo specs."""
    from build123d import Align, Cylinder

    params = horn_disc_params(servo)
    if params is None:
        return None

    return Cylinder(
        params.radius,
        params.thickness,
        align=(Align.CENTER, Align.CENTER, Align.CENTER),
    )


def _orient_z_to_axis(solid, axis: tuple[float, float, float]):
    """Rotate a solid from Z-up to align with the given axis.

    Uses .moved() (not .locate()) so any existing z-offset on the solid
    is preserved and composed with the rotation.
    """
    from build123d import Location

    ax, ay, az = axis
    mag = math.sqrt(ax * ax + ay * ay + az * az)
    if mag < 1e-9:
        return solid
    ax, ay, az = ax / mag, ay / mag, az / mag

    # If already aligned with Z, no rotation needed
    if abs(az) > 0.999:
        if az < 0:
            # 180° around X
            return solid.moved(Location((0, 0, 0), (180, 0, 0)))
        return solid

    # Compute rotation from Z to target axis
    # Cross product of Z and target = rotation axis
    # Z = (0,0,1), target = (ax,ay,az)
    # cross = (-ay, ax, 0), angle = acos(az)
    angle_deg = math.degrees(math.acos(max(-1.0, min(1.0, az))))
    # Rotation axis in XY plane
    rot_axis_x = -ay
    rot_axis_y = ax
    rot_mag = math.sqrt(rot_axis_x**2 + rot_axis_y**2)
    if rot_mag < 1e-9:
        return solid

    rot_axis_x /= rot_mag
    rot_axis_y /= rot_mag

    # Convert axis-angle to Euler angles for build123d Location
    quat = _axis_angle_to_quat((rot_axis_x, rot_axis_y, 0.0), math.radians(angle_deg))
    euler = _quat_to_euler(quat)
    return solid.moved(Location((0, 0, 0), euler))


def _axis_angle_to_quat(
    axis: tuple[float, float, float], angle: float
) -> tuple[float, float, float, float]:
    """Convert axis-angle to quaternion (w, x, y, z)."""
    half = angle / 2
    s = math.sin(half)
    return (math.cos(half), axis[0] * s, axis[1] * s, axis[2] * s)


def _quat_to_euler(q: Quat) -> tuple[float, float, float]:
    """Convert quaternion (w, x, y, z) to Euler angles (rx, ry, rz) in degrees.

    Uses intrinsic XYZ convention matching build123d's Location(pos, euler).
    """
    w, x, y, z = q

    # Roll (X)
    sinr_cosp = 2.0 * (w * x + y * z)
    cosr_cosp = 1.0 - 2.0 * (x * x + y * y)
    rx = math.atan2(sinr_cosp, cosr_cosp)

    # Pitch (Y)
    sinp = 2.0 * (w * y - z * x)
    sinp = max(-1.0, min(1.0, sinp))
    ry = math.asin(sinp)

    # Yaw (Z)
    siny_cosp = 2.0 * (w * z + x * y)
    cosy_cosp = 1.0 - 2.0 * (y * y + z * z)
    rz = math.atan2(siny_cosp, cosy_cosp)

    return (math.degrees(rx), math.degrees(ry), math.degrees(rz))


def emit_cad_for_module(bot: Bot, module_name: str, output_dir: Path) -> None:
    """Export a per-module STEP file containing only parts in the named module."""
    from build123d import Compound, export_step

    assembly_parts = getattr(bot, "_assembly_parts", [])
    part_modules = getattr(bot, "_part_modules", [])

    module_parts = [
        part for part, mod in zip(assembly_parts, part_modules) if mod == module_name
    ]

    if module_parts:
        assembly = Compound(label=f"{bot.name}_{module_name}", children=module_parts)
        filename = f"assembly_{module_name}.step"
        export_step(assembly, str(output_dir / filename))
        print(f"CAD: wrote {filename} ({len(module_parts)} parts)")
