"""CAD emitter — generates STEP assembly + per-body STLs using build123d.

Primary mesh generator for the bot. Creates:
- Per-body solid geometry (structural shells with servo brackets unioned in)
- Full assembly STEP export (viewable in FreeCAD, Fusion 360)
- Per-body STL export (referenced by MuJoCo XML for simulation visuals)

Bracket geometry is generated by botcad.bracket and unioned into the parent
body solid at each joint location. The bracket includes the servo pocket,
shaft clearance, screw holes, and cable exit — so no separate pocket cutting
is needed here.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

from botcad.bracket import BracketSpec, bracket_solid
from botcad.geometry import servo_placement

if TYPE_CHECKING:
    from botcad.geometry import Quat
    from botcad.skeleton import Body, Bot, Joint


def emit_cad(bot: Bot, output_dir: Path) -> None:
    """Generate STEP assembly and per-body STL files."""
    from build123d import Compound, export_step, export_stl

    meshes_dir = output_dir / "meshes"
    meshes_dir.mkdir(parents=True, exist_ok=True)

    # Build body → parent joint mapping for mesh origin offsets
    parent_joint_map: dict[str, Joint] = {}
    for joint in bot.all_joints:
        if joint.child is not None:
            parent_joint_map[joint.child.name] = joint

    parts: dict[str, object] = {}

    for body in bot.all_bodies:
        pj = parent_joint_map.get(body.name)
        solid = _make_body_solid(body, pj)
        if solid is not None:
            parts[body.name] = solid
            stl_path = meshes_dir / f"{body.name}.stl"
            export_stl(solid, str(stl_path))

    if parts:
        assembly = Compound(children=list(parts.values()))
        step_path = output_dir / "assembly.step"
        export_step(assembly, str(step_path))
        print(f"CAD: wrote assembly.step + {len(parts)} STLs to {output_dir}")


def _make_body_solid(body: Body, parent_joint: Joint | None = None):
    """Create a build123d solid for a body.

    Returns a Solid with:
    - Structural shell (hollow box/cylinder/tube/sphere)
    - Servo brackets unioned in at each joint location
    - Component pockets cut out

    Mesh origin conventions (matching MuJoCo emitter expectations):
    - box/sphere/cylinder: centered at origin
    - tube: offset so z=0 is the joint end, z=+length is the far end
    """
    from build123d import Align, Box, Cylinder, Location, Sphere

    dims = body.dimensions
    wall = 0.002  # 2mm wall thickness

    if body.shape == "cylinder":
        r = body.radius or dims[0] / 2
        h = body.width or dims[2]
        outer = Cylinder(r, h, align=(Align.CENTER, Align.CENTER, Align.CENTER))
        if r > wall and h > wall * 2:
            inner = Cylinder(
                r - wall,
                h - wall * 2,
                align=(Align.CENTER, Align.CENTER, Align.CENTER),
            )
            shell = outer - inner
        else:
            shell = outer

        # Orient cylinder along parent joint's rotation axis
        if parent_joint is not None:
            shell = _orient_z_to_axis(shell, parent_joint.axis)

    elif body.shape == "tube":
        r = body.outer_r or dims[0] / 2
        length = body.length or dims[2]
        outer = Cylinder(r, length, align=(Align.CENTER, Align.CENTER, Align.CENTER))
        inner_r = max(r - wall, r * 0.6)
        inner = Cylinder(
            inner_r,
            length + 0.001,
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
        )
        shell = outer - inner
        # Offset tube so z=0 is the joint end, z=+length is the far end
        shell = shell.locate(Location((0, 0, length / 2)))

    elif body.shape == "sphere":
        r = body.radius or dims[0] / 2
        shell = Sphere(r)

    else:
        # Box shell
        outer = Box(
            dims[0],
            dims[1],
            dims[2],
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
        )
        if all(d > wall * 2 for d in dims):
            inner = Box(
                dims[0] - wall * 2,
                dims[1] - wall * 2,
                dims[2] - wall * 2,
                align=(Align.CENTER, Align.CENTER, Align.CENTER),
            )
            shell = outer - inner
        else:
            shell = outer

    # Cut component pockets
    for mount in body.mounts:
        cd = mount.component.dimensions
        pocket = Box(
            cd[0] + 0.0005,
            cd[1] + 0.0005,
            cd[2] + 0.0005,
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
        )
        pocket = pocket.locate(Location(mount.resolved_pos))
        shell = shell - pocket

    # Union servo brackets at each joint
    bracket_spec = BracketSpec()
    for joint in body.joints:
        servo = joint.servo
        center, quat = servo_placement(
            servo.shaft_offset, servo.shaft_axis, joint.axis, joint.pos
        )
        euler = _quat_to_euler(quat)

        bracket = bracket_solid(servo, bracket_spec)
        bracket = bracket.locate(Location(center, euler))
        shell = shell + bracket

    return shell


def _orient_z_to_axis(solid, axis: tuple[float, float, float]):
    """Rotate a solid from Z-up to align with the given axis."""
    from build123d import Location

    ax, ay, az = axis
    mag = math.sqrt(ax * ax + ay * ay + az * az)
    if mag < 1e-9:
        return solid
    ax, ay, az = ax / mag, ay / mag, az / mag

    # If already aligned with Z, no rotation needed
    if abs(az) > 0.999:
        if az < 0:
            # 180° around X
            return solid.locate(Location((0, 0, 0), (180, 0, 0)))
        return solid

    # Compute rotation from Z to target axis
    # Using the same approach as _quat_to_euler but computing Euler directly
    # Cross product of Z and target = rotation axis
    # Z = (0,0,1), target = (ax,ay,az)
    # cross = (-ay, ax, 0), angle = acos(az)
    angle_deg = math.degrees(math.acos(max(-1.0, min(1.0, az))))
    # Rotation axis in XY plane
    rot_axis_x = -ay
    rot_axis_y = ax
    rot_mag = math.sqrt(rot_axis_x**2 + rot_axis_y**2)
    if rot_mag < 1e-9:
        return solid

    rot_axis_x /= rot_mag
    rot_axis_y /= rot_mag

    # Convert axis-angle to Euler angles for build123d Location
    # For a rotation around an axis in the XY plane by angle theta:
    quat = _axis_angle_to_quat((rot_axis_x, rot_axis_y, 0.0), math.radians(angle_deg))
    euler = _quat_to_euler(quat)
    return solid.locate(Location((0, 0, 0), euler))


def _axis_angle_to_quat(
    axis: tuple[float, float, float], angle: float
) -> tuple[float, float, float, float]:
    """Convert axis-angle to quaternion (w, x, y, z)."""
    half = angle / 2
    s = math.sin(half)
    return (math.cos(half), axis[0] * s, axis[1] * s, axis[2] * s)


def _quat_to_euler(q: Quat) -> tuple[float, float, float]:
    """Convert quaternion (w, x, y, z) to Euler angles (rx, ry, rz) in degrees.

    Uses intrinsic XYZ convention matching build123d's Location(pos, euler).
    """
    w, x, y, z = q

    # Roll (X)
    sinr_cosp = 2.0 * (w * x + y * z)
    cosr_cosp = 1.0 - 2.0 * (x * x + y * y)
    rx = math.atan2(sinr_cosp, cosr_cosp)

    # Pitch (Y)
    sinp = 2.0 * (w * y - z * x)
    sinp = max(-1.0, min(1.0, sinp))
    ry = math.asin(sinp)

    # Yaw (Z)
    siny_cosp = 2.0 * (w * z + x * y)
    cosy_cosp = 1.0 - 2.0 * (y * y + z * z)
    rz = math.atan2(siny_cosp, cosy_cosp)

    return (math.degrees(rx), math.degrees(ry), math.degrees(rz))
