"""Assembly guide emitter — generates assembly_guide.md from a Bot."""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

from botcad.component import CameraSpec

if TYPE_CHECKING:
    from botcad.skeleton import Body, Bot


def emit_assembly_guide(bot: Bot, output_dir: Path) -> None:
    """Generate assembly_guide.md with wiring diagram and assembly steps."""
    lines: list[str] = []
    lines.append(f"# Assembly Guide — {bot.name}\n")
    lines.append("*Auto-generated by botcad*\n")

    # ── Servo bus configuration ──────────────────────────────────────
    lines.append("## Servo Bus Configuration\n")
    lines.append(
        "STS3215 servos are daisy-chained on a single UART half-duplex bus. "
        "Each servo needs a unique ID programmed via the Feetech debug board "
        "or the Waveshare controller software.\n"
    )
    lines.append("| Servo ID | Joint | Mode | Range |")
    lines.append("|----------|-------|------|-------|")

    for i, joint in enumerate(bot.all_joints, start=1):
        mode = "Continuous" if joint.servo.continuous else "Position"
        lo, hi = joint.effective_range
        range_deg = f"{math.degrees(lo):.0f}° to {math.degrees(hi):.0f}°"
        lines.append(f"| {i} | {joint.name} | {mode} | {range_deg} |")

    # ── Range of motion diagram ─────────────────────────────────────
    lines.append("\n## Joint Range of Motion\n")
    lines.append("```")
    _emit_rom_diagram(lines, bot)
    lines.append("```\n")

    # ── Wiring diagram — derived from actual components ──────────────
    lines.append("\n## Wiring Diagram\n")

    # Discover what's actually mounted
    has_pi = False
    has_camera = False
    has_controller = False
    for body in bot.all_bodies:
        for mount in body.mounts:
            if isinstance(mount.component, CameraSpec):
                has_camera = True
            elif mount.component.name == "RaspberryPiZero2W":
                has_pi = True
            elif mount.component.name == "WaveshareSerialBus":
                has_controller = True

    lines.append("```")

    if has_controller and not has_pi:
        # Typical SO-101 setup: USB from host PC to Waveshare controller
        lines.append("Host PC (USB)")
        lines.append("  └── USB-C → Waveshare Serial Bus Servo Driver Board")
        lines.append("")
        lines.append(f"Power Supply ({bot.all_joints[0].servo.voltage:.0f}V)")
        lines.append("  └── Barrel jack → Waveshare board → Servo bus power")
    elif has_pi:
        # Onboard compute setup (wheeler_arm style)
        lines.append("Battery (LiPo 2S, 7.4V)")
        lines.append("  ├── XT30 → Servo bus power (direct 7.4V)")
        lines.append("  └── XT30 → 5V Buck converter → Raspberry Pi USB power")
        lines.append("")
        lines.append("Raspberry Pi Zero 2W")
        lines.append("  ├── GPIO 14 (TX) → Servo bus UART (via level shifter to 5V)")
        if has_camera:
            lines.append("  └── CSI connector → Camera ribbon cable → OV5647")
    else:
        lines.append("Power Supply")
        lines.append("  └── Servo bus power")

    lines.append("")
    lines.append("Servo Daisy Chain:")
    if has_controller:
        chain_parts = ["Waveshare board"]
    elif has_pi:
        chain_parts = ["Pi UART"]
    else:
        chain_parts = ["Controller"]
    for i, joint in enumerate(bot.all_joints, start=1):
        chain_parts.append(f"ID{i}({joint.name})")
    lines.append("  " + " → ".join(chain_parts))
    lines.append("```\n")

    # ── Printed parts ────────────────────────────────────────────────
    lines.append("## 3D Printed Parts\n")
    lines.append(
        "Print all body shells from the STL files in `meshes/`. "
        "Recommended: PLA+, 0.4mm nozzle, 0.2mm layer height, 15–20% infill.\n"
    )
    lines.append("| Part | STL File | Shape | Dimensions (mm) |")
    lines.append("|------|----------|-------|-----------------|")
    for body in bot.all_bodies:
        dims = body.dimensions
        dims_str = f"{dims[0] * 1000:.1f} x {dims[1] * 1000:.1f} x {dims[2] * 1000:.1f}"
        lines.append(
            f"| {body.name} | `meshes/{body.name}.stl` | {body.shape} | {dims_str} |"
        )
    lines.append("")

    # ── Assembly sequence — full kinematic tree ──────────────────────
    lines.append("## Assembly Sequence\n")

    step = [1]  # mutable counter for nested function

    # Step 1: Program servo IDs
    lines.append(
        f"{step[0]}. **Program servo IDs** — Connect each STS3215 individually "
        "to the Feetech debug board or Waveshare controller and assign IDs 1–"
        f"{len(bot.all_joints)} as listed above.\n"
    )
    step[0] += 1

    # Step 2: Print parts
    lines.append(
        f"{step[0]}. **Print structural parts** — Print all {len(bot.all_bodies)} "
        "body shells from the STL files listed above.\n"
    )
    step[0] += 1

    # Step 3+: Assemble the kinematic tree
    if bot.root:
        _emit_assembly_steps(lines, bot.root, bot, step, is_root=True)

    # Wire routing
    lines.append(
        f"{step[0]}. **Route servo bus cable** — Daisy-chain all servos following "
        "the wiring diagram above. Route cables through/along each structural "
        "member.\n"
    )
    step[0] += 1

    # Power
    if has_controller:
        lines.append(
            f"{step[0]}. **Connect power** — Connect {bot.all_joints[0].servo.voltage:.0f}V "
            "power supply to the Waveshare board barrel jack. Connect USB-C "
            "cable from host PC.\n"
        )
    elif has_pi:
        lines.append(
            f"{step[0]}. **Connect power** — Battery XT30 to servo bus power + "
            "buck converter → Pi USB.\n"
        )
    else:
        lines.append(
            f"{step[0]}. **Connect power** — Connect power supply to servo bus.\n"
        )
    step[0] += 1

    # Camera (only if present)
    if has_camera:
        lines.append(
            f"{step[0]}. **Connect camera** — Route CSI ribbon cable from "
            "OV5647 to Pi.\n"
        )
        step[0] += 1

    # Fixed-base mounting
    if bot.base_type == "fixed":
        lines.append(
            f"{step[0]}. **Mount to table** — Secure the base plate to a flat "
            "surface using table clamps (150mm+ opening recommended) or M4 "
            "bolts through the base plate mounting holes.\n"
        )
        step[0] += 1

    # Test
    lines.append(f"{step[0]}. **Test** — Power on and verify all servo IDs respond. ")
    if has_controller:
        lines.append(
            "   Use the Waveshare controller software or "
            "`python -m lerobot.scripts.control_robot` to test each joint.\n"
        )
    elif has_pi:
        test_msg = "   Run `sts3215_scan.py` to verify servos"
        if has_camera:
            test_msg += ", test camera with `rpicam-hello`."
        else:
            test_msg += "."
        lines.append(test_msg + "\n")

    text = "\n".join(lines) + "\n"
    (output_dir / "assembly_guide.md").write_text(text)
    print(f"Assembly guide: wrote assembly_guide.md to {output_dir}")


def _emit_assembly_steps(
    lines: list[str],
    body: Body,
    bot: Bot,
    step: list[int],
    is_root: bool = False,
) -> None:
    """Recursively emit assembly steps for the kinematic tree."""
    if is_root:
        lines.append(f"{step[0]}. **Assemble base** (`{body.name}`):")
        for mount in body.mounts:
            lines.append(
                f"   - Mount {mount.component.name} ({mount.label}) "
                f"at {mount.position} position"
            )
        if not body.mounts:
            lines.append(f"   - Base plate body ({body.shape})")
        lines.append("")
        step[0] += 1

    for joint in body.joints:
        if joint.child is None:
            continue
        child = joint.child

        # Describe the attachment
        lines.append(
            f"{step[0]}. **Attach {child.name}** to {body.name} "
            f"via {joint.servo.name} at joint `{joint.name}` "
            f"(axis: {_axis_label(joint.axis)}):"
        )
        lines.append(
            f"   - Screw servo into {body.name} bracket using M3 mounting screws"
        )
        lines.append(
            f"   - Attach {child.name} bracket to servo horn using M2.5 horn screws"
        )

        # Mention any mounted components
        for mount in child.mounts:
            lines.append(
                f"   - Mount {mount.component.name} ({mount.label}) "
                f"at {mount.position} position"
            )
        lines.append("")
        step[0] += 1

        # Recurse into child body's joints
        _emit_assembly_steps(lines, child, bot, step)


def _axis_label(axis: tuple[float, float, float]) -> str:
    """Human-readable axis label."""
    x, y, z = axis
    if abs(z) > 0.9:
        return "vertical" if z > 0 else "vertical (inverted)"
    if abs(y) > 0.9:
        return "pitch" if y > 0 else "pitch (inverted)"
    if abs(x) > 0.9:
        return "roll" if x > 0 else "roll (inverted)"
    return f"({x:.1f}, {y:.1f}, {z:.1f})"


def _emit_rom_diagram(lines: list[str], bot: Bot) -> None:
    """Emit an ASCII range-of-motion diagram for all joints.

    Example output:
        -180°       -90°         0°        +90°       +180°
          |          |          |          |          |
    shoulder_pan   ████████████████████████  ±110°
    shoulder_lift     ███████████████████    ±100°
    ...
    """
    bar_width = 40  # characters for the [-180, +180] scale
    scale_min = -180.0
    scale_max = 180.0
    scale_range = scale_max - scale_min

    # Header: scale labels
    # Place markers at -180, -90, 0, +90, +180
    markers = [-180, -90, 0, 90, 180]
    header = " " * 18  # joint name padding
    tick_line = " " * 18
    for m in markers:
        col = int((m - scale_min) / scale_range * bar_width)
        label = f"{m:+d}°" if m != 0 else "0°"
        # Center the label on the column
        start = col - len(label) // 2
        while len(header) < 18 + start:
            header += " "
        header += label
        while len(tick_line) < 18 + col:
            tick_line += " "
        tick_line += "|"

    lines.append(header)
    lines.append(tick_line)

    # Find max joint name length for alignment
    max_name = max((len(j.name) for j in bot.all_joints), default=10)
    pad = max(max_name + 2, 18)

    for joint in bot.all_joints:
        lo, hi = joint.effective_range
        lo_deg = math.degrees(lo)
        hi_deg = math.degrees(hi)

        # Clamp to scale
        lo_clamped = max(lo_deg, scale_min)
        hi_clamped = min(hi_deg, scale_max)

        # Convert to bar positions
        start_col = int((lo_clamped - scale_min) / scale_range * bar_width)
        end_col = int((hi_clamped - scale_min) / scale_range * bar_width)
        start_col = max(0, min(bar_width - 1, start_col))
        end_col = max(start_col + 1, min(bar_width, end_col))

        # Build the bar
        bar = [" "] * bar_width
        for c in range(start_col, end_col):
            bar[c] = "█"

        # Range summary
        if abs(lo_deg + hi_deg) < 1.0:
            range_str = f"±{hi_deg:.0f}°"
        else:
            range_str = f"{lo_deg:+.0f}° to {hi_deg:+.0f}°"

        name_padded = joint.name.ljust(pad - 2) + "  "
        lines.append(f"{name_padded}{''.join(bar)}  {range_str}")


def emit_assembly_guide_for_module(
    bot: Bot, module_name: str, output_dir: Path
) -> None:
    """Generate a per-module assembly guide (subset of the full guide)."""
    bodies = bot._module_bodies(module_name)
    joints = bot._module_joints(module_name)
    if not bodies:
        return

    lines: list[str] = []
    lines.append(f"# Assembly Guide — {bot.name} / {module_name}\n")
    lines.append("*Auto-generated by botcad*\n")

    lines.append("## Parts in this module\n")
    for body in bodies:
        dims = body.dimensions
        dims_str = f"{dims[0] * 1000:.1f} x {dims[1] * 1000:.1f} x {dims[2] * 1000:.1f}"
        lines.append(f"- **{body.name}** ({body.shape}, {dims_str} mm)")
    lines.append("")

    lines.append("## Joints\n")
    for j in joints:
        lo, hi = j.effective_range
        lines.append(
            f"- **{j.name}** — {j.servo.name}, "
            f"{math.degrees(lo):.0f}° to {math.degrees(hi):.0f}°"
        )
    lines.append("")

    text = "\n".join(lines) + "\n"
    filename = f"assembly_guide_{module_name}.md"
    (output_dir / filename).write_text(text)
    print(f"Assembly guide: wrote {filename}")
