"""Assembly guide emitter — generates assembly_guide.md from a Bot."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from botcad.skeleton import Bot


def _build_guide_lines(bodies: list, joints: list, root_body, title: str) -> list[str]:
    """Build assembly guide markdown lines from a set of bodies and joints."""
    import math

    lines: list[str] = []
    lines.append(f"# Assembly Guide — {title}\n")
    lines.append("*Auto-generated by botcad*\n")

    # Servo bus IDs
    lines.append("## Servo Bus Configuration\n")
    lines.append(
        "STS3215 servos are daisy-chained on a single UART half-duplex bus. "
        "Each servo needs a unique ID programmed via the Feetech debug board.\n"
    )
    lines.append("| Servo ID | Joint | Mode | Range |")
    lines.append("|----------|-------|------|-------|")

    for i, joint in enumerate(joints, start=1):
        mode = "Continuous" if joint.servo.continuous else "Position"
        lo, hi = joint.effective_range
        range_deg = f"{math.degrees(lo):.0f}° to {math.degrees(hi):.0f}°"
        lines.append(f"| {i} | {joint.name} | {mode} | {range_deg} |")

    # Servo daisy chain
    lines.append("\n## Servo Daisy Chain\n")
    lines.append("```")
    chain_parts = []
    for i, joint in enumerate(joints, start=1):
        chain_parts.append(f"ID{i}({joint.name})")
    lines.append("  " + " → ".join(chain_parts) if chain_parts else "  (none)")
    lines.append("```\n")

    # Assembly sequence
    lines.append("## Assembly Sequence\n")

    step = 1
    if joints:
        lines.append(
            f"{step}. **Program servo IDs** — Connect each STS3215 individually "
            "to the Feetech debug board and assign IDs as listed above.\n"
        )
        step += 1

    lines.append(
        f"{step}. **Print structural parts** — Print body shells from the "
        "STL files in `meshes/`. Recommended: PLA or PETG, 0.2mm layer height, "
        "20% infill.\n"
    )
    step += 1

    # Mount components in root body
    if root_body is not None:
        lines.append(f"{step}. **Assemble root body** (`{root_body.name}`):")
        for mount in root_body.mounts:
            lines.append(
                f"   - Mount {mount.component.name} ({mount.label}) "
                f"at {mount.position} position"
            )
        lines.append("")
        step += 1

    # Build body set for filtering
    body_names = {b.name for b in bodies}

    # Attach child bodies (walk all bodies looking for joints to children in our set)
    for body in bodies:
        for joint in body.joints:
            if joint.child is not None and joint.child.name in body_names:
                lines.append(
                    f"{step}. **Attach {joint.child.name}** via {joint.servo.name} "
                    f"at joint `{joint.name}`"
                )
                if joint.child.mounts:
                    for mount in joint.child.mounts:
                        lines.append(
                            f"   - Mount {mount.component.name} ({mount.label})"
                        )
                # Recurse one level for sub-joints within the set
                for sub_joint in joint.child.joints:
                    if (
                        sub_joint.child is not None
                        and sub_joint.child.name in body_names
                    ):
                        lines.append(
                            f"   - Attach {sub_joint.child.name} via "
                            f"{sub_joint.servo.name} at `{sub_joint.name}`"
                        )
                lines.append("")
                step += 1

    lines.append(
        f"{step}. **Route servo bus cable** — Daisy-chain servos following "
        "the wiring diagram. Use the cable channel in each structural member.\n"
    )

    return lines


def emit_assembly_guide(bot: Bot, output_dir: Path) -> None:
    """Generate assembly_guide.md with wiring diagram and assembly steps."""
    lines = _build_guide_lines(bot.all_bodies, bot.all_joints, bot.root, bot.name)

    # Full-bot wiring diagram (only in full guide)
    # Insert before assembly sequence
    wiring_lines: list[str] = []
    wiring_lines.append("\n## Wiring Diagram\n")
    wiring_lines.append("```")
    wiring_lines.append("Battery (LiPo 2S, 7.4V)")
    wiring_lines.append("  ├── XT30 → Servo bus power (direct 7.4V)")
    wiring_lines.append("  └── XT30 → 5V Buck converter → Raspberry Pi USB power")
    wiring_lines.append("")
    wiring_lines.append("Raspberry Pi Zero 2W")
    wiring_lines.append("  ├── GPIO 14 (TX) → Servo bus UART (via level shifter to 5V)")
    wiring_lines.append("  └── CSI connector → Camera ribbon cable → OV5647")
    wiring_lines.append("```\n")

    # Find insertion point (after servo daisy chain, before assembly sequence)
    insert_idx = None
    for i, line in enumerate(lines):
        if line.startswith("## Assembly Sequence"):
            insert_idx = i
            break
    if insert_idx is not None:
        lines[insert_idx:insert_idx] = wiring_lines

    # Add final test steps
    step_num = lines[-1].split(".")[0].strip() if lines else "1"
    try:
        next_step = int(step_num) + 1
    except ValueError:
        next_step = 99

    lines.append(
        f"{next_step}. **Connect camera** — Route CSI ribbon cable from OV5647 to Pi.\n"
    )
    next_step += 1
    lines.append(
        f"{next_step}. **Connect power** — Battery XT30 to servo bus power + "
        "buck converter → Pi USB.\n"
    )
    next_step += 1
    lines.append(
        f"{next_step}. **Test** — Power on, verify all servo IDs respond via "
        "`sts3215_scan.py`, test camera with `rpicam-hello`.\n"
    )

    text = "\n".join(lines) + "\n"
    (output_dir / "assembly_guide.md").write_text(text)
    print(f"Assembly guide: wrote assembly_guide.md to {output_dir}")


def emit_assembly_guide_for_module(
    bot: Bot, module_name: str, output_dir: Path
) -> None:
    """Generate a per-module assembly guide."""
    bodies = bot._module_bodies(module_name)
    joints = bot._module_joints(module_name)
    if not bodies:
        return

    root_body = bodies[0]  # first body in tree order
    title = f"{bot.name} / {module_name}"
    lines = _build_guide_lines(bodies, joints, root_body, title)

    text = "\n".join(lines) + "\n"
    filename = f"assembly_guide_{module_name}.md"
    (output_dir / filename).write_text(text)
    print(f"Assembly guide: wrote {filename}")
