"""Assembly guide emitter — generates assembly_guide.md from a Bot."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from botcad.skeleton import Bot


def emit_assembly_guide(bot: Bot, output_dir: Path) -> None:
    """Generate assembly_guide.md with wiring diagram and assembly steps."""
    lines: list[str] = []
    lines.append(f"# Assembly Guide — {bot.name}\n")
    lines.append("*Auto-generated by botcad*\n")

    # Servo bus IDs
    lines.append("## Servo Bus Configuration\n")
    lines.append(
        "STS3215 servos are daisy-chained on a single UART half-duplex bus. "
        "Each servo needs a unique ID programmed via the Feetech debug board.\n"
    )
    lines.append("| Servo ID | Joint | Mode | Range |")
    lines.append("|----------|-------|------|-------|")

    for i, joint in enumerate(bot.all_joints, start=1):
        mode = "Continuous" if joint.servo.continuous else "Position"
        lo, hi = joint.effective_range
        import math

        range_deg = f"{math.degrees(lo):.0f}° to {math.degrees(hi):.0f}°"
        lines.append(f"| {i} | {joint.name} | {mode} | {range_deg} |")

    # Wiring diagram
    lines.append("\n## Wiring Diagram\n")
    lines.append("```")
    lines.append("Battery (LiPo 2S, 7.4V)")
    lines.append("  ├── XT30 → Servo bus power (direct 7.4V)")
    lines.append("  └── XT30 → 5V Buck converter → Raspberry Pi USB power")
    lines.append("")
    lines.append("Raspberry Pi Zero 2W")
    lines.append("  ├── GPIO 14 (TX) → Servo bus UART (via level shifter to 5V)")
    lines.append("  └── CSI connector → Camera ribbon cable → OV5647")
    lines.append("")

    # Servo daisy chain
    lines.append("Servo Daisy Chain:")
    chain_parts = ["Pi UART"]
    for i, joint in enumerate(bot.all_joints, start=1):
        chain_parts.append(f"ID{i}({joint.name})")
    lines.append("  " + " → ".join(chain_parts))
    lines.append("```\n")

    # Assembly sequence
    lines.append("## Assembly Sequence\n")

    step = 1
    lines.append(
        f"{step}. **Program servo IDs** — Connect each STS3215 individually "
        "to the Feetech debug board and assign IDs 1–N as listed above.\n"
    )
    step += 1

    lines.append(
        f"{step}. **Print structural parts** — Print all body shells from the "
        "STL files in `meshes/`. Recommended: PLA or PETG, 0.2mm layer height, "
        "20% infill.\n"
    )
    step += 1

    # Mount components in order
    lines.append(f"{step}. **Assemble base body** (`{bot.root.name}`):")
    if bot.root:
        for mount in bot.root.mounts:
            lines.append(
                f"   - Mount {mount.component.name} ({mount.label}) "
                f"at {mount.position} position"
            )
    lines.append("")
    step += 1

    # Attach child bodies
    if bot.root:
        for joint in bot.root.joints:
            if joint.child is not None:
                lines.append(
                    f"{step}. **Attach {joint.child.name}** via {joint.servo.name} "
                    f"at joint `{joint.name}`"
                )
                if joint.child.mounts:
                    for mount in joint.child.mounts:
                        lines.append(
                            f"   - Mount {mount.component.name} ({mount.label})"
                        )
                # Recurse one level for arm joints
                for sub_joint in joint.child.joints:
                    if sub_joint.child is not None:
                        lines.append(
                            f"   - Attach {sub_joint.child.name} via "
                            f"{sub_joint.servo.name} at `{sub_joint.name}`"
                        )
                lines.append("")
                step += 1

    lines.append(
        f"{step}. **Route servo bus cable** — Daisy-chain all servos following "
        "the wiring diagram above. Use the cable channel in each structural member.\n"
    )
    step += 1

    lines.append(
        f"{step}. **Connect camera** — Route CSI ribbon cable from OV5647 to Pi.\n"
    )
    step += 1

    lines.append(
        f"{step}. **Connect power** — Battery XT30 to servo bus power + "
        "buck converter → Pi USB.\n"
    )
    step += 1

    lines.append(
        f"{step}. **Test** — Power on, verify all servo IDs respond via "
        "`sts3215_scan.py`, test camera with `rpicam-hello`.\n"
    )

    text = "\n".join(lines) + "\n"
    (output_dir / "assembly_guide.md").write_text(text)
    print(f"Assembly guide: wrote assembly_guide.md to {output_dir}")
