/**
 * Stress Mode — Visualizes FEA results (stress heatmaps and debug voxels).
 *
 * Loads vertex-colored PLY files generated by the Warp FEA pipeline.
 */

import * as THREE from 'three';
import { PLYLoader } from 'three/examples/jsm/loaders/PLYLoader';
import type { ViewerContext, ViewerMode } from './types.ts';

export class StressMode implements ViewerMode {
  ctx: ViewerContext;
  active: boolean = false;
  stressGroup: THREE.Group;
  loader: PLYLoader;
  loadedFiles: Set<string> = new Set();

  constructor(ctx: ViewerContext) {
    this.ctx = ctx;
    this.stressGroup = new THREE.Group();
    this.stressGroup.name = 'FEA Stress Overlays';
    this.loader = new PLYLoader();
  }

  activate() {
    this.active = true;
    this.ctx.scene.add(this.stressGroup);
    
    // Sync stress group to bot position
    this.stressGroup.position.copy(this.ctx.mujocoRoot.position);
    this.stressGroup.quaternion.copy(this.ctx.mujocoRoot.quaternion);
    this.stressGroup.scale.copy(this.ctx.mujocoRoot.scale);
    this.stressGroup.updateWorldMatrix(true, true);

    // Dim the main bot to make the stress heatmap pop
    this.ctx.botScene.ghostAll();
    this.ctx.syncScene();
    
    this._showStressPanel();
  }

  deactivate() {
    this.active = false;
    this.ctx.scene.remove(this.stressGroup);
    
    // Restore bot visibility
    this.ctx.botScene.unghost();
    this.ctx.syncScene();
    
    const panel = document.getElementById('side-panel');
    if (panel) panel.innerHTML = '';
  }

  _showStressPanel() {
    const panel = document.getElementById('side-panel');
    if (!panel) return;

    let html = '<h2>Stress Analysis</h2>';
    html += '<p style="font-size:12px;color:#5C7080;margin-bottom:16px;">Visualizing 3D stress propagation from Warp FEM.</p>';
    
    html += '<h3>Overlays</h3>';
    html += '<div class="prop-grid">';
    html += `
      <div style="margin-bottom:8px;">
        <label style="display:flex;align-items:center;gap:8px;font-size:12px;color:#A7B6C2;">
          <input type="checkbox" id="toggle-heatmap" checked> Stress Heatmap (PLY)
        </label>
      </div>
      <div style="margin-bottom:8px;">
        <label style="display:flex;align-items:center;gap:8px;font-size:12px;color:#A7B6C2;">
          <input type="checkbox" id="toggle-voxels"> Debug Voxels (Bolt/Push)
        </label>
      </div>
    `;
    html += '</div>';
    
    html += '<button id="load-fea-btn" class="btn btn-sm btn-primary" style="margin-top:16px;width:100%;">Load FEA Results</button>';

    panel.innerHTML = html;

    document.getElementById('load-fea-btn')?.addEventListener('click', () => this.loadAllFEA());
    
    document.getElementById('toggle-heatmap')?.addEventListener('change', (e) => {
        this.stressGroup.traverse((child) => {
            if (child.name.includes('heatmap')) child.visible = (e.target as HTMLInputElement).checked;
        });
    });
    
    document.getElementById('toggle-voxels')?.addEventListener('change', (e) => {
        this.stressGroup.traverse((child) => {
            if (child.name.includes('voxels')) child.visible = (e.target as HTMLInputElement).checked;
        });
    });
  }

  async loadAllFEA() {
    // In a real integration, we'd fetch paths from the manifest.
    // For the POC, we assume standard filenames in the bot's folder.
    const baseUrl = `../bots/${this.ctx.botName}`;
    
    const files = [
        { name: 'stress_heatmap.ply', label: 'heatmap' },
        { name: 'fixed_voxels.ply', label: 'voxels_fixed' },
        { name: 'loaded_voxels.ply', label: 'voxels_loaded' },
        { name: 'structure_voxels.ply', label: 'voxels_structure' }
    ];

    for (const file of files) {
        try {
            await this.loadPLY(`${baseUrl}/${file.name}`, file.label);
        } catch (err) {
            console.warn(`Could not load FEA file ${file.name}:`, err);
        }
    }
  }

  async loadPLY(url: string, label: string) {
    if (this.loadedFiles.has(url)) return;

    return new Promise((resolve, reject) => {
      this.loader.load(url, (geometry) => {
        geometry.computeVertexNormals();
        
        const material = new THREE.MeshPhongMaterial({ 
            vertexColors: true,
            transparent: label.includes('structure'),
            opacity: label.includes('structure') ? 0.3 : 1.0,
            shininess: 10
        });
        
        const mesh = new THREE.Mesh(geometry, material);
        mesh.name = label;
        
        // Match the bot's coordinate system (assuming FEA is in world or local)
        // For the POC, scripts/test_bracket_fea.py uses world-ish CAD coords.
        this.stressGroup.add(mesh);
        this.loadedFiles.add(url);
        resolve(mesh);
      }, undefined, reject);
    });
  }

  update() {
    // Keep overlays synced if the bot moves (though FEA is usually static for a pose)
  }
}
